import XCTest
@testable import shouldrest

final class LocalizationQualityTests: XCTestCase {
    func testSimplifiedChineseUsesNaturalCoreRestTerms() {
        L10n.languageOverride = "zh-Hans"
        defer { L10n.languageOverride = nil }

        XCTAssertEqual(L10n.tr("kind.eyeGate"), "护眼休息")
        XCTAssertEqual(L10n.tr("kind.bodyBreak"), "活动休息")
        XCTAssertEqual(L10n.tr("prefs.enableEyeGate"), "启用护眼休息")
        XCTAssertEqual(L10n.tr("prefs.enableBodyBreak"), "启用活动休息")
        XCTAssertEqual(L10n.tr("prefs.language"), "界面语言")
        XCTAssertEqual(L10n.tr("prefs.activeRestShortcut.body"), "管理活动休息")
        XCTAssertEqual(L10n.tr("prefs.activeRestShortcut.eye"), "完成护眼休息")
        XCTAssertEqual(L10n.tr("overlay.ready"), "就绪")
    }

    func testSimplifiedChineseVisibleValuesAvoidUntranslatedCoreTerms() throws {
        let values = try simplifiedChineseLocalizedValues().joined(separator: "\n")

        for forbiddenTerm in ["Eye Gate", "Body Break", "Focus /", "Mac-first", "skip/postpone"] {
            XCTAssertFalse(values.contains(forbiddenTerm), "Unexpected untranslated term: \(forbiddenTerm)")
        }
    }

    func testSimplifiedChineseEmergencyCopyUsesExitInsteadOfOverride() throws {
        let values = try simplifiedChineseLocalizedValues().joined(separator: "\n")

        XCTAssertTrue(values.contains("紧急退出"))
        XCTAssertFalse(values.contains("紧急覆盖"))
    }

    func testVisiblePreferenceCopyAvoidsImplementationTerms() throws {
        defer { L10n.languageOverride = nil }

        let simplifiedChineseValues = try localizedValues(language: "zh-Hans").joined(separator: "\n")
        let englishValues = try localizedValues(language: "en").joined(separator: "\n")
        let simplifiedChineseLines = simplifiedChineseValues.components(separatedBy: "\n")
        let englishLines = englishValues.components(separatedBy: "\n")

        XCTAssertFalse(simplifiedChineseValues.contains("语言覆盖"))
        XCTAssertFalse(simplifiedChineseValues.contains("结束当前活动休息"))
        XCTAssertFalse(simplifiedChineseValues.contains("结束当前休息"))
        XCTAssertFalse(simplifiedChineseValues.contains("可用等待"))
        XCTAssertFalse(simplifiedChineseValues.contains("暂停切换"))
        XCTAssertFalse(simplifiedChineseValues.contains("原始规则 JSON"))
        XCTAssertFalse(simplifiedChineseValues.contains("原始提示 JSON"))
        XCTAssertFalse(simplifiedChineseValues.contains("复制调试信息"))
        XCTAssertFalse(simplifiedChineseValues.contains("调试面板"))
        XCTAssertFalse(simplifiedChineseValues.contains("ShouldRest 调试"))
        XCTAssertFalse(simplifiedChineseValues.contains("调试信息"))
        XCTAssertFalse(simplifiedChineseValues.contains("管理员："))
        XCTAssertFalse(simplifiedChineseValues.contains("身体休息"))
        XCTAssertFalse(simplifiedChineseLines.contains("名称"))
        XCTAssertFalse(simplifiedChineseValues.contains("匹配词"))
        XCTAssertFalse(simplifiedChineseLines.contains("模式"))
        XCTAssertFalse(simplifiedChineseLines.contains("添加规则"))
        XCTAssertFalse(simplifiedChineseLines.contains("更新规则"))
        XCTAssertFalse(simplifiedChineseLines.contains("当前规则"))
        XCTAssertFalse(simplifiedChineseValues.contains("加入轮换"))
        XCTAssertFalse(simplifiedChineseValues.contains("更新轮换"))
        XCTAssertFalse(simplifiedChineseValues.contains("当前轮换"))
        XCTAssertFalse(simplifiedChineseValues.contains("立即护眼休息"))
        XCTAssertFalse(simplifiedChineseValues.contains("立即活动休息"))
        XCTAssertFalse(simplifiedChineseValues.contains("手动完成"))
        XCTAssertFalse(simplifiedChineseValues.contains("手动暂停"))
        XCTAssertFalse(simplifiedChineseValues.contains("睡眠或锁屏时暂停调度"))
        XCTAssertFalse(simplifiedChineseLines.contains("确认无限期暂停"))
        XCTAssertFalse(englishValues.contains("Language override"))
        XCTAssertFalse(englishLines.contains("Name"))
        XCTAssertFalse(englishLines.contains("Match terms"))
        XCTAssertFalse(englishValues.contains("match terms"))
        XCTAssertFalse(englishLines.contains("Mode"))
        XCTAssertFalse(englishLines.contains("Add Rule"))
        XCTAssertFalse(englishLines.contains("Update Rule"))
        XCTAssertFalse(englishLines.contains("Current rules"))
        XCTAssertFalse(englishValues.contains("available after"))
        XCTAssertFalse(englishValues.contains("Body start sound"))
        XCTAssertFalse(englishValues.contains("Body finish sound"))
        XCTAssertFalse(englishValues.contains("Pause toggle"))
        XCTAssertFalse(englishValues.contains("Raw rule JSON"))
        XCTAssertFalse(englishValues.contains("Raw idea JSON"))
        XCTAssertFalse(englishValues.contains("App rules JSON"))
        XCTAssertFalse(englishValues.contains("Ideas JSON"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("json editor"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("json array"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("valid json"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("raw rule json"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("raw idea json"))
        XCTAssertFalse(englishValues.contains("Copy Debug Info"))
        XCTAssertFalse(englishValues.contains("Debug Panel"))
        XCTAssertFalse(englishValues.contains("ShouldRest Debug"))
        XCTAssertFalse(englishValues.contains("Debug Info"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("runtime flags"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("diagnostic snapshot"))
        XCTAssertFalse(englishValues.contains("blocking the app"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("app exclusion"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("app exclusions"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("end active rest"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("deferred rest"))
        XCTAssertFalse(englishValues.contains("Admin:"))
        XCTAssertFalse(englishValues.contains("debug, and preference"))
        XCTAssertFalse(englishValues.contains("Add to Rotation"))
        XCTAssertFalse(englishValues.contains("Update Rotation"))
        XCTAssertFalse(englishValues.contains("Current rotation"))
        XCTAssertFalse(englishValues.contains("Take Eye Gate Now"))
        XCTAssertFalse(englishValues.contains("Take Body Break Now"))
        XCTAssertFalse(englishValues.contains("Take Next Scheduled Rest Now"))
        XCTAssertFalse(englishValues.contains("Pause-until-morning mode"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("manual finish"))
        XCTAssertFalse(englishValues.contains("Manual pause"))
        XCTAssertFalse(englishValues.contains("Click Again to Pause Indefinitely"))
        XCTAssertFalse(englishValues.contains("Confirm Pause Indefinitely"))
        XCTAssertFalse(englishValues.contains("Resume at hour"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("scheduler"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("danger indicator"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("danger score"))
        XCTAssertFalse(englishValues.contains("Eye Gate(s)"))
        XCTAssertFalse(englishValues.contains("%ds remaining"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("deadlock"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("one-shot automation tasks"))
        XCTAssertFalse(englishValues.contains("Stretchly-compatible"))
        XCTAssertFalse(englishValues.contains("Frequent Eyes"))
        XCTAssertFalse(englishValues.contains("Learn More"))
        XCTAssertFalse(englishValues.contains("Use Selected"))
        XCTAssertFalse(englishValues.contains("..."))
        XCTAssertFalse(simplifiedChineseValues.contains("恢复小时"))
        XCTAssertFalse(simplifiedChineseValues.contains("危险值"))
        XCTAssertFalse(simplifiedChineseValues.contains("锁死"))
        XCTAssertFalse(simplifiedChineseValues.contains("兼容 Stretchly"))
        XCTAssertFalse(simplifiedChineseValues.contains("运行时标记"))
        XCTAssertFalse(simplifiedChineseValues.contains("诊断快照"))
        XCTAssertFalse(simplifiedChineseValues.contains("阻塞应用"))
        XCTAssertFalse(simplifiedChineseValues.contains("应用排除"))
        XCTAssertFalse(simplifiedChineseValues.contains("JSON 编辑器"))
        XCTAssertFalse(simplifiedChineseValues.contains("有效 JSON"))
        XCTAssertFalse(simplifiedChineseValues.contains("一次性自动化任务"))
        XCTAssertFalse(simplifiedChineseValues.contains("再次点击确认无限期暂停"))
        XCTAssertFalse(simplifiedChineseValues.contains("..."))

        XCTAssertTrue(englishValues.contains("Body Break start sound"))
        XCTAssertTrue(englishValues.contains("Body Break finish sound"))
        XCTAssertTrue(englishValues.contains("Pause until morning"))
        XCTAssertTrue(englishValues.contains("Pause or resume"))
        XCTAssertTrue(englishValues.contains("Finish Eye Gate or manage Body Break"))
        XCTAssertTrue(englishValues.contains("Manage Body Break"))
        XCTAssertTrue(englishValues.contains("delayed rest"))
        XCTAssertTrue(englishValues.contains("Indefinitely…"))
        XCTAssertTrue(englishValues.contains("Resume hour"))
        XCTAssertTrue(englishValues.contains("Show rest pressure indicator"))
        XCTAssertTrue(englishValues.contains("Pressure %d/10"))
        XCTAssertTrue(englishValues.contains("Next Body Break after %d Eye Gates"))
        XCTAssertTrue(englishValues.contains("%@ active, %@ remaining"))
        XCTAssertTrue(englishValues.contains("Balanced"))
        XCTAssertTrue(englishValues.contains("More Eye Rests"))
        XCTAssertTrue(englishValues.contains("About ShouldRest"))
        XCTAssertTrue(englishValues.contains("Full-featured controls"))
        XCTAssertTrue(englishValues.contains("Emergency stays in the overlay"))
        XCTAssertTrue(englishValues.contains("Start With This Rhythm"))
        XCTAssertTrue(englishValues.contains("Add Idea"))
        XCTAssertTrue(englishValues.contains("Update Idea"))
        XCTAssertTrue(englishValues.contains("Custom ideas"))
        XCTAssertTrue(englishValues.contains("Rule name"))
        XCTAssertTrue(englishValues.contains("App Rules"))
        XCTAssertTrue(englishValues.contains("Enable app rules"))
        XCTAssertTrue(englishValues.contains("Apps to match"))
        XCTAssertTrue(englishValues.contains("Matched app behavior"))
        XCTAssertTrue(englishValues.contains("Add App Rule"))
        XCTAssertTrue(englishValues.contains("Update App Rule"))
        XCTAssertTrue(englishValues.contains("Saved app rules"))
        XCTAssertTrue(englishValues.contains("App rules bulk edit"))
        XCTAssertTrue(englishValues.contains("Bulk Edit App Rules"))
        XCTAssertTrue(englishValues.contains("Ideas bulk edit"))
        XCTAssertTrue(englishValues.contains("Bulk Edit Ideas"))
        XCTAssertTrue(englishValues.contains("Bulk edit content has an invalid format"))
        XCTAssertFalse(englishValues.contains("Open Advanced App Rule Editor"))
        XCTAssertFalse(englishValues.contains("Open Advanced Idea Editor"))
        XCTAssertTrue(englishValues.contains("Copy Diagnostics"))
        XCTAssertTrue(englishValues.contains("ShouldRest Diagnostics"))
        XCTAssertTrue(englishValues.contains("Diagnostics"))
        XCTAssertTrue(englishValues.contains("Current rest state, app paths, and settings for troubleshooting."))
        XCTAssertTrue(englishValues.contains("ShouldRest is ready"))
        XCTAssertTrue(englishValues.contains("Start Eye Gate Now"))
        XCTAssertTrue(englishValues.contains("Start Body Break Now"))
        XCTAssertTrue(englishValues.contains("Start Next Rest Now"))
        XCTAssertTrue(englishValues.contains("Start Eye Gate"))
        XCTAssertTrue(englishValues.contains("Start Body Break"))
        XCTAssertTrue(englishValues.contains("pending automation requests"))
        XCTAssertTrue(simplifiedChineseValues.contains("暂停到早晨方式"))
        XCTAssertTrue(simplifiedChineseValues.contains("暂停或恢复"))
        XCTAssertTrue(simplifiedChineseValues.contains("完成护眼休息或管理活动休息"))
        XCTAssertTrue(simplifiedChineseValues.contains("管理活动休息"))
        XCTAssertTrue(simplifiedChineseValues.contains("无限期暂停…"))
        XCTAssertTrue(simplifiedChineseValues.contains("恢复时间"))
        XCTAssertTrue(simplifiedChineseValues.contains("显示休息压力指示器"))
        XCTAssertTrue(simplifiedChineseValues.contains("压力 %d/10"))
        XCTAssertTrue(simplifiedChineseValues.contains("均衡"))
        XCTAssertTrue(simplifiedChineseValues.contains("更多护眼"))
        XCTAssertTrue(simplifiedChineseValues.contains("关于 ShouldRest"))
        XCTAssertTrue(simplifiedChineseValues.contains("完整控制能力"))
        XCTAssertTrue(simplifiedChineseValues.contains("覆盖层内紧急退出"))
        XCTAssertTrue(simplifiedChineseValues.contains("使用这个节奏开始"))
        XCTAssertTrue(simplifiedChineseValues.contains("添加提示"))
        XCTAssertTrue(simplifiedChineseValues.contains("更新提示"))
        XCTAssertTrue(simplifiedChineseValues.contains("自定义提示"))
        XCTAssertTrue(simplifiedChineseValues.contains("规则名称"))
        XCTAssertTrue(simplifiedChineseValues.contains("应用规则"))
        XCTAssertTrue(simplifiedChineseValues.contains("匹配应用"))
        XCTAssertTrue(simplifiedChineseValues.contains("匹配时行为"))
        XCTAssertTrue(simplifiedChineseValues.contains("添加应用规则"))
        XCTAssertTrue(simplifiedChineseValues.contains("更新应用规则"))
        XCTAssertTrue(simplifiedChineseValues.contains("已保存应用规则"))
        XCTAssertFalse(simplifiedChineseValues.contains("应用规则 JSON"))
        XCTAssertFalse(simplifiedChineseValues.contains("提示 JSON"))
        XCTAssertFalse(simplifiedChineseValues.contains("JSON 数组"))
        XCTAssertTrue(simplifiedChineseValues.contains("应用规则批量编辑"))
        XCTAssertTrue(simplifiedChineseValues.contains("批量编辑应用规则"))
        XCTAssertTrue(simplifiedChineseValues.contains("提示批量编辑"))
        XCTAssertTrue(simplifiedChineseValues.contains("批量编辑提示"))
        XCTAssertTrue(simplifiedChineseValues.contains("批量编辑内容格式无效"))
        XCTAssertFalse(simplifiedChineseValues.contains("打开高级应用规则编辑器"))
        XCTAssertFalse(simplifiedChineseValues.contains("打开高级提示编辑器"))
        XCTAssertTrue(simplifiedChineseValues.contains("复制诊断信息"))
        XCTAssertTrue(simplifiedChineseValues.contains("ShouldRest 诊断"))
        XCTAssertTrue(simplifiedChineseValues.contains("诊断"))
        XCTAssertTrue(simplifiedChineseValues.contains("当前休息状态、应用路径和设置，用于排查问题。"))
        XCTAssertTrue(simplifiedChineseValues.contains("ShouldRest 已就绪"))
        XCTAssertTrue(simplifiedChineseValues.contains("立即开始护眼休息"))
        XCTAssertTrue(simplifiedChineseValues.contains("立即开始活动休息"))
        XCTAssertTrue(simplifiedChineseValues.contains("待处理的自动化请求"))

        L10n.languageOverride = "en"
        XCTAssertEqual(L10n.tr("prefs.eyeGateNow"), "Start Eye Gate")
        XCTAssertEqual(L10n.tr("prefs.bodyBreakNow"), "Start Body Break")
        XCTAssertEqual(L10n.tr("prefs.activeRestShortcut.eyeAndBody"), "Finish Eye Gate or manage Body Break")
        XCTAssertEqual(L10n.tr("prefs.activeRestShortcut.body"), "Manage Body Break")
        XCTAssertEqual(L10n.tr("prefs.activeRestShortcut.eye"), "Finish Eye Gate")
        XCTAssertEqual(L10n.tr("prefs.name"), "Rule name")
        XCTAssertEqual(L10n.tr("prefs.matchTerms"), "Apps to match")
        XCTAssertEqual(L10n.tr("prefs.mode"), "Matched app behavior")
        XCTAssertEqual(L10n.tr("prefs.addAppExclusionRule"), "Add App Rule")
        XCTAssertEqual(L10n.tr("prefs.updateAppExclusionRule"), "Update App Rule")
        XCTAssertEqual(L10n.tr("prefs.appExclusionRules"), "Saved app rules")
        XCTAssertEqual(L10n.tr("prefs.sectionExclusion"), "App Rules")
        XCTAssertEqual(L10n.tr("prefs.enablePrimaryExclusion"), "Enable app rules")
        XCTAssertEqual(L10n.tr("prefs.advancedRulesJSON"), "App rules bulk edit")
        XCTAssertEqual(L10n.tr("prefs.showAdvancedRules"), "Bulk Edit App Rules")
        XCTAssertEqual(L10n.tr("prefs.advancedIdeasJSON"), "Ideas bulk edit")
        XCTAssertEqual(L10n.tr("prefs.showAdvancedIdeas"), "Bulk Edit Ideas")
        XCTAssertEqual(L10n.tr("prefs.invalidJSONTitle"), "Bulk edit content has an invalid format")
        XCTAssertEqual(L10n.tr("prefs.adminHideUpdates"), "Hide update UI")
        XCTAssertEqual(L10n.tr("prefs.adminHideSettingsPath"), "Hide settings, log, support, and image paths")
        XCTAssertEqual(L10n.tr("prefs.adminHideStrict"), "Hide strict preferences")
        XCTAssertEqual(L10n.tr("prefs.imagePreviewEmpty"), "Drop or choose an image")
        XCTAssertEqual(L10n.tr("prefs.noImageSelected"), "Drop or choose an image")
        XCTAssertEqual(L10n.tr("prefs.eyeManualFinish"), "Wait for me after Eye Gate ends")
        XCTAssertEqual(L10n.tr("prefs.manualFinish"), "Wait for me after Body Break ends")
        XCTAssertEqual(L10n.tr("status.pauseReason.user"), "Paused by you")
        XCTAssertTrue(L10n.tr("prefs.eyeManualFinishHelp").contains("Early dismissal stays disabled"))
        XCTAssertTrue(L10n.tr("prefs.bodyManualFinishHelp").contains("instead of closing immediately"))
        XCTAssertEqual(L10n.tr("menu.copyDebug"), "Copy Diagnostics")
        XCTAssertEqual(L10n.tr("menu.debugPanel"), "Diagnostics…")
        XCTAssertEqual(L10n.tr("debug.title"), "ShouldRest Diagnostics")
        XCTAssertEqual(L10n.tr("debug.openLog"), "Reveal Log")
        XCTAssertEqual(L10n.tr("debug.openSettings"), "Reveal Settings")
        XCTAssertTrue(L10n.tr("debug.summaryEyeActiveBody").localizedCaseInsensitiveContains("Emergency Exit twice"))
        XCTAssertTrue(L10n.tr("debug.summaryEyeActiveBody").localizedCaseInsensitiveContains("Esc twice"))
        XCTAssertFalse(L10n.tr("debug.summaryEyeActiveBody").localizedCaseInsensitiveContains("Esc once"))
        XCTAssertEqual(L10n.tr("about.debug"), "Diagnostics")
        XCTAssertEqual(L10n.tr("about.compatibilityTitle"), "Full-featured controls")
        XCTAssertTrue(L10n.tr("reset.confirmBody").contains("delayed rest"))
        XCTAssertTrue(L10n.tr("reset.confirmBody").contains("pending automation requests"))
        XCTAssertFalse(L10n.tr("reset.confirmBody").localizedCaseInsensitiveContains("deferred rest"))
        XCTAssertFalse(L10n.tr("reset.confirmBody").localizedCaseInsensitiveContains("one-shot automation tasks"))
        XCTAssertNotEqual(L10n.tr("prefs.imagePreviewEmpty"), "No image selected")
        XCTAssertNotEqual(L10n.tr("prefs.eyeManualFinish"), "Manual finish after Eye Gate duration")
        XCTAssertNotEqual(L10n.tr("prefs.manualFinish"), "Manual finish after Body Break duration")
        XCTAssertNotEqual(L10n.tr("prefs.eyeGateNow"), "Eye Gate now")
        XCTAssertNotEqual(L10n.tr("prefs.bodyBreakNow"), "Body Break now")

        L10n.languageOverride = "zh-Hans"
        XCTAssertEqual(L10n.tr("prefs.eyeGateNow"), "立即开始护眼休息")
        XCTAssertEqual(L10n.tr("prefs.bodyBreakNow"), "立即开始活动休息")
        XCTAssertEqual(L10n.tr("prefs.activeRestShortcut.eyeAndBody"), "完成护眼休息或管理活动休息")
        XCTAssertEqual(L10n.tr("prefs.activeRestShortcut.body"), "管理活动休息")
        XCTAssertEqual(L10n.tr("prefs.activeRestShortcut.eye"), "完成护眼休息")
        XCTAssertEqual(L10n.tr("prefs.name"), "规则名称")
        XCTAssertEqual(L10n.tr("prefs.matchTerms"), "匹配应用")
        XCTAssertEqual(L10n.tr("prefs.mode"), "匹配时行为")
        XCTAssertEqual(L10n.tr("prefs.addAppExclusionRule"), "添加应用规则")
        XCTAssertEqual(L10n.tr("prefs.updateAppExclusionRule"), "更新应用规则")
        XCTAssertEqual(L10n.tr("prefs.appExclusionRules"), "已保存应用规则")
        XCTAssertEqual(L10n.tr("prefs.sectionExclusion"), "应用规则")
        XCTAssertEqual(L10n.tr("prefs.enablePrimaryExclusion"), "启用应用规则")
        XCTAssertEqual(L10n.tr("prefs.advancedRulesJSON"), "应用规则批量编辑")
        XCTAssertEqual(L10n.tr("prefs.showAdvancedRules"), "批量编辑应用规则")
        XCTAssertEqual(L10n.tr("prefs.advancedIdeasJSON"), "提示批量编辑")
        XCTAssertEqual(L10n.tr("prefs.showAdvancedIdeas"), "批量编辑提示")
        XCTAssertEqual(L10n.tr("prefs.invalidJSONTitle"), "批量编辑内容格式无效")
        XCTAssertEqual(L10n.tr("prefs.adminHideUpdates"), "隐藏更新界面")
        XCTAssertEqual(L10n.tr("prefs.adminHideSettingsPath"), "隐藏设置、日志、支持与图片路径")
        XCTAssertEqual(L10n.tr("prefs.adminHideStrict"), "隐藏严格模式偏好")
        XCTAssertEqual(L10n.tr("prefs.imagePreviewEmpty"), "拖入或选择图片")
        XCTAssertEqual(L10n.tr("prefs.noImageSelected"), "拖入或选择图片")
        XCTAssertEqual(L10n.tr("prefs.eyeManualFinish"), "护眼休息计时结束后等我完成")
        XCTAssertEqual(L10n.tr("prefs.manualFinish"), "活动休息计时结束后等我完成")
        XCTAssertEqual(L10n.tr("status.pauseReason.user"), "你已暂停")
        XCTAssertTrue(L10n.tr("prefs.eyeManualFinishHelp").contains("仍然不能提前结束"))
        XCTAssertTrue(L10n.tr("prefs.bodyManualFinishHelp").contains("不是立即关闭"))
        XCTAssertEqual(L10n.tr("menu.copyDebug"), "复制诊断信息")
        XCTAssertEqual(L10n.tr("menu.debugPanel"), "诊断…")
        XCTAssertEqual(L10n.tr("debug.title"), "ShouldRest 诊断")
        XCTAssertEqual(L10n.tr("debug.openLog"), "显示日志")
        XCTAssertEqual(L10n.tr("debug.openSettings"), "显示设置文件")
        XCTAssertTrue(L10n.tr("debug.summaryEyeActiveBody").contains("紧急退出两次"))
        XCTAssertTrue(L10n.tr("debug.summaryEyeActiveBody").contains("两次 Esc"))
        XCTAssertFalse(L10n.tr("debug.summaryEyeActiveBody").contains("按一次 Esc"))
        XCTAssertEqual(L10n.tr("about.debug"), "诊断")
        XCTAssertEqual(L10n.tr("about.compatibilityTitle"), "完整控制能力")
        XCTAssertTrue(L10n.tr("reset.confirmBody").contains("待处理的自动化请求"))
        XCTAssertFalse(L10n.tr("reset.confirmBody").contains("一次性自动化任务"))
        XCTAssertNotEqual(L10n.tr("prefs.imagePreviewEmpty"), "未选择图片")
        XCTAssertNotEqual(L10n.tr("prefs.eyeManualFinish"), "护眼休息到时后手动完成")
        XCTAssertNotEqual(L10n.tr("prefs.manualFinish"), "活动休息到时后手动完成")
        L10n.languageOverride = nil
    }

    func testEmergencyCopyUsesInternalConfirmationWithoutCountdownOrExternalWindow() {
        defer { L10n.languageOverride = nil }

        L10n.languageOverride = "en"
        XCTAssertEqual(L10n.tr("overlay.emergencyOverride"), "Emergency Exit · Esc")
        XCTAssertEqual(L10n.tr("overlay.emergencyOverrideConfirm"), "Click again · Esc again")
        XCTAssertEqual(L10n.tr("overlay.emergencyOverrideArmed"), "Click again · Esc again")
        XCTAssertTrue(L10n.tr("overlay.emergencyOverrideConfirm").contains("Esc"))
        XCTAssertTrue(L10n.tr("overlay.emergencyOverrideHelp").contains("inside the overlay"))
        XCTAssertTrue(L10n.tr("prefs.eyeEmergencyOverrideHelp").contains("inside the overlay"))
        XCTAssertTrue(L10n.tr("prefs.eyeEmergencyOverrideHelp").localizedCaseInsensitiveContains("second click"))
        XCTAssertFalse(L10n.tr("prefs.eyeEmergencyOverrideHelp").localizedCaseInsensitiveContains("hold"))
        XCTAssertFalse(L10n.tr("prefs.eyeEmergencyOverrideHelp").localizedCaseInsensitiveContains("another window"))
        XCTAssertTrue(L10n.tr("menu.emergencyOverrideHelp").localizedCaseInsensitiveContains("two clicks"))
        XCTAssertFalse(L10n.tr("menu.emergencyOverrideHelp").localizedCaseInsensitiveContains("arm"))
        XCTAssertTrue(L10n.tr("cli.help").contains("Bring the active Eye Gate overlay forward for Emergency Exit."))
        XCTAssertTrue(L10n.tr("cli.requestedEmergency").contains("inside the overlay"))
        XCTAssertTrue(L10n.tr("cli.requestedEmergency").localizedCaseInsensitiveContains("two clicks"))
        XCTAssertFalse(L10n.tr("cli.requestedEmergency").localizedCaseInsensitiveContains("another window"))
        XCTAssertFalse(L10n.tr("cli.requestedEmergency").localizedCaseInsensitiveContains("hold"))
        XCTAssertFalse(L10n.tr("cli.help").localizedCaseInsensitiveContains("run it again"))
        XCTAssertTrue(L10n.tr("onboarding.emergencyFeatureBody").contains("external requests only bring it forward"))
        XCTAssertTrue(L10n.tr("onboarding.emergencyFeatureBody").localizedCaseInsensitiveContains("two clicks"))
        XCTAssertFalse(L10n.tr("onboarding.emergencyFeatureBody").localizedCaseInsensitiveContains("countdown"))
        XCTAssertTrue(L10n.tr("onboarding.emergencyFeatureBody").localizedCaseInsensitiveContains("without asking you to click another window"))

        L10n.languageOverride = "zh-Hans"
        XCTAssertEqual(L10n.tr("overlay.emergencyOverride"), "紧急退出 · Esc")
        XCTAssertEqual(L10n.tr("overlay.emergencyOverrideConfirm"), "再点一次 · 再按 Esc")
        XCTAssertEqual(L10n.tr("overlay.emergencyOverrideArmed"), "再点一次 · 再按 Esc")
        XCTAssertTrue(L10n.tr("overlay.emergencyOverrideConfirm").contains("Esc"))
        XCTAssertTrue(L10n.tr("overlay.emergencyOverrideHelp").contains("覆盖层内"))
        XCTAssertTrue(L10n.tr("prefs.eyeEmergencyOverrideHelp").contains("覆盖层内"))
        XCTAssertTrue(L10n.tr("prefs.eyeEmergencyOverrideHelp").contains("第二次点击"))
        XCTAssertFalse(L10n.tr("prefs.eyeEmergencyOverrideHelp").contains("长按"))
        XCTAssertFalse(L10n.tr("prefs.eyeEmergencyOverrideHelp").contains("按住"))
        XCTAssertFalse(L10n.tr("prefs.eyeEmergencyOverrideHelp").contains("另一个窗口"))
        XCTAssertTrue(L10n.tr("menu.emergencyOverrideHelp").contains("点两次"))
        XCTAssertFalse(L10n.tr("menu.emergencyOverrideHelp").contains("待确认"))
        XCTAssertTrue(L10n.tr("cli.help").contains("把当前护眼覆盖层带到前台以便紧急退出"))
        XCTAssertTrue(L10n.tr("cli.requestedEmergency").contains("覆盖层内"))
        XCTAssertTrue(L10n.tr("cli.requestedEmergency").contains("点两次"))
        XCTAssertFalse(L10n.tr("cli.requestedEmergency").contains("另一个窗口"))
        XCTAssertFalse(L10n.tr("cli.requestedEmergency").contains("长按"))
        XCTAssertFalse(L10n.tr("cli.help").contains("再次运行"))
        XCTAssertTrue(L10n.tr("onboarding.emergencyFeatureBody").contains("外部请求只会把覆盖层带到前台"))
        XCTAssertTrue(L10n.tr("onboarding.emergencyFeatureBody").contains("点两次"))
        XCTAssertFalse(L10n.tr("onboarding.emergencyFeatureBody").contains("倒计时"))
        XCTAssertTrue(L10n.tr("onboarding.emergencyFeatureBody").contains("不再要求你点击另一个窗口"))
    }

    func testOnboardingPrimaryActionNamesSelectedRhythm() {
        defer { L10n.languageOverride = nil }

        L10n.languageOverride = "en"
        XCTAssertEqual(
            L10n.format("onboarding.useSelectedWithPreset", "More Eye Rests"),
            "Start With More Eye Rests"
        )

        L10n.languageOverride = "zh-Hans"
        XCTAssertEqual(
            L10n.format("onboarding.useSelectedWithPreset", "更多护眼休息"),
            "使用更多护眼休息开始"
        )
    }

    func testBlockedActionNotificationsUseUserActionLanguage() {
        defer { L10n.languageOverride = nil }

        L10n.languageOverride = "en"
        XCTAssertEqual(L10n.tr("menu.reset"), "Reset Schedule")
        XCTAssertEqual(L10n.tr("menu.emergencyOverlayOnly"), "Use Emergency Exit in the overlay")
        XCTAssertTrue(L10n.tr("menu.emergencyOverlayOnlyHelp").contains("This menu cannot exit"))
        XCTAssertTrue(L10n.tr("menu.emergencyOverlayOnlyHelp").contains("lower-right Emergency Exit twice"))
        XCTAssertTrue(L10n.tr("menu.emergencyOverlayOnlyHelp").contains("Esc twice"))
        XCTAssertEqual(
            L10n.tr("status.eyeGateActiveGuidance"),
            "Click Emergency Exit twice in the overlay, or press Esc twice."
        )
        XCTAssertEqual(L10n.tr("status.eyeGateActiveNoEmergencyGuidance"), "Keep looking away until the timer ends.")
        XCTAssertEqual(L10n.tr("status.eyeGateReadyGuidance"), "Finish from the overlay when ready.")
        XCTAssertEqual(
            L10n.tr("status.bodyBreakActiveGuidance"),
            "Use overlay controls to postpone, skip, or finish."
        )
        XCTAssertEqual(L10n.tr("prefs.reset"), "Reset Schedule")
        XCTAssertEqual(L10n.format("notification.quitBlocked", "Eye Gate"), "Finish Eye Gate before quitting.")
        XCTAssertEqual(
            L10n.tr("notification.quitBlockedEyeGateEmergency"),
            "Use Emergency Exit in the overlay to quit during Eye Gate. Click Emergency Exit twice or press Esc twice; this records a missed rest."
        )
        XCTAssertTrue(L10n.tr("notification.quitBlockedEyeGateEmergency").contains("Emergency Exit in the overlay"))
        XCTAssertTrue(L10n.tr("notification.quitBlockedEyeGateEmergency").contains("Emergency Exit twice"))
        XCTAssertTrue(L10n.tr("notification.quitBlockedEyeGateEmergency").contains("Esc twice"))
        XCTAssertTrue(L10n.tr("notification.quitBlockedEyeGateEmergency").contains("missed rest"))
        XCTAssertEqual(L10n.format("notification.resetBlocked", "Eye Gate"), "Finish Eye Gate before resetting the schedule.")
        XCTAssertEqual(L10n.format("notification.pauseBlocked", "Eye Gate"), "Finish Eye Gate before pausing.")
        XCTAssertFalse(L10n.tr("notification.quitBlocked").localizedCaseInsensitiveContains("strict"))
        XCTAssertFalse(L10n.tr("notification.quitBlockedEyeGateEmergency").localizedCaseInsensitiveContains("hold"))
        XCTAssertFalse(L10n.tr("notification.quitBlockedEyeGateEmergency").localizedCaseInsensitiveContains("another window"))
        XCTAssertFalse(L10n.tr("notification.resetBlocked").localizedCaseInsensitiveContains("strict"))
        XCTAssertFalse(L10n.tr("notification.pauseBlocked").localizedCaseInsensitiveContains("strict"))
        XCTAssertFalse(L10n.tr("notification.resetBlocked").localizedCaseInsensitiveContains("breaks"))

        L10n.languageOverride = "zh-Hans"
        XCTAssertEqual(L10n.tr("menu.reset"), "重置计划")
        XCTAssertEqual(L10n.tr("menu.emergencyOverlayOnly"), "在覆盖层内使用紧急退出")
        XCTAssertTrue(L10n.tr("menu.emergencyOverlayOnlyHelp").contains("此菜单不能退出"))
        XCTAssertTrue(L10n.tr("menu.emergencyOverlayOnlyHelp").contains("右下角"))
        XCTAssertTrue(L10n.tr("menu.emergencyOverlayOnlyHelp").contains("紧急退出两次"))
        XCTAssertTrue(L10n.tr("menu.emergencyOverlayOnlyHelp").contains("两次 Esc"))
        XCTAssertEqual(L10n.tr("status.eyeGateActiveGuidance"), "在覆盖层内点击紧急退出两次，或按两次 Esc。")
        XCTAssertEqual(L10n.tr("status.eyeGateActiveNoEmergencyGuidance"), "计时结束前，请继续看向屏幕外。")
        XCTAssertEqual(L10n.tr("status.eyeGateReadyGuidance"), "准备好后，从覆盖层内完成休息。")
        XCTAssertEqual(L10n.tr("status.bodyBreakActiveGuidance"), "使用覆盖层按钮推迟、跳过或完成。")
        XCTAssertEqual(L10n.tr("prefs.reset"), "重置计划")
        XCTAssertEqual(L10n.format("notification.quitBlocked", "护眼休息"), "请先完成护眼休息，再退出。")
        XCTAssertEqual(
            L10n.tr("notification.quitBlockedEyeGateEmergency"),
            "要在护眼休息中退出，请在覆盖层内点击紧急退出两次，或按两次 Esc；这会记录一次未完成休息。"
        )
        XCTAssertTrue(L10n.tr("notification.quitBlockedEyeGateEmergency").contains("覆盖层内点击紧急退出两次"))
        XCTAssertTrue(L10n.tr("notification.quitBlockedEyeGateEmergency").contains("两次 Esc"))
        XCTAssertTrue(L10n.tr("notification.quitBlockedEyeGateEmergency").contains("未完成休息"))
        XCTAssertEqual(L10n.format("notification.resetBlocked", "护眼休息"), "请先完成护眼休息，再重置计划。")
        XCTAssertEqual(L10n.format("notification.pauseBlocked", "护眼休息"), "请先完成护眼休息，再暂停。")
        XCTAssertFalse(L10n.tr("notification.quitBlocked").contains("严格"))
        XCTAssertFalse(L10n.tr("notification.quitBlockedEyeGateEmergency").contains("长按"))
        XCTAssertFalse(L10n.tr("notification.quitBlockedEyeGateEmergency").contains("另一个窗口"))
        XCTAssertFalse(L10n.tr("notification.resetBlocked").contains("严格"))
        XCTAssertFalse(L10n.tr("notification.pauseBlocked").contains("严格"))
    }

    func testRestoreDefaultsConfirmationNamesTheDestructiveAction() {
        defer { L10n.languageOverride = nil }

        L10n.languageOverride = "en"
        XCTAssertEqual(L10n.tr("prefs.restoreDefaultsContinue"), "Restore Defaults")
        XCTAssertTrue(L10n.tr("prefs.restoreDefaultsWarning").contains("current preferences"))
        XCTAssertFalse(L10n.tr("prefs.restoreDefaultsContinue").localizedCaseInsensitiveContains("continue"))

        L10n.languageOverride = "zh-Hans"
        XCTAssertEqual(L10n.tr("prefs.restoreDefaultsContinue"), "恢复默认")
        XCTAssertTrue(L10n.tr("prefs.restoreDefaultsWarning").contains("当前偏好设置"))
        XCTAssertFalse(L10n.tr("prefs.restoreDefaultsContinue").contains("继续"))
    }

    private func simplifiedChineseLocalizedValues() throws -> [String] {
        try localizedValues(language: "zh-Hans")
    }

    private func localizedValues(language: String) throws -> [String] {
        let testFileURL = URL(fileURLWithPath: #filePath)
        let packageRoot = testFileURL
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let stringsURL = packageRoot
            .appendingPathComponent("Sources/shouldrest/Resources/\(language).lproj/Localizable.strings")
        let content = try String(contentsOf: stringsURL, encoding: .utf8)
        return content
            .components(separatedBy: .newlines)
            .compactMap { line in
                guard let separatorRange = line.range(of: "=") else { return nil }
                return String(line[separatorRange.upperBound...])
            }
    }
}
