import XCTest
@testable import shouldrest

final class LocalizationQualityTests: XCTestCase {
    func testSimplifiedChineseUsesNaturalCoreRestTerms() {
        L10n.languageOverride = "zh-Hans"
        defer { L10n.languageOverride = nil }

        XCTAssertEqual(L10n.tr("kind.eyeGate"), "护眼休息")
        XCTAssertEqual(L10n.tr("kind.bodyBreak"), "活动休息")
        XCTAssertEqual(L10n.tr("prefs.enableEyeGate"), "启用护眼休息")
        XCTAssertEqual(L10n.tr("prefs.enableBodyBreak"), "启用活动休息")
        XCTAssertEqual(L10n.tr("prefs.language"), "界面语言")
        XCTAssertEqual(L10n.tr("prefs.activeRestShortcut.body"), "管理活动休息")
        XCTAssertEqual(L10n.tr("prefs.activeRestShortcut.eye"), "完成护眼休息")
        XCTAssertEqual(L10n.tr("overlay.ready"), "就绪")
    }

    func testEnglishOverlayReadyStatusUsesPolishedStateCopy() {
        L10n.languageOverride = "en"
        defer { L10n.languageOverride = nil }

        XCTAssertEqual(L10n.tr("overlay.ready"), "Ready")
        XCTAssertEqual(L10n.tr("overlay.eyeCompleteTitle"), "Eye Gate Complete")
        XCTAssertEqual(L10n.tr("overlay.bodyCompleteTitle"), "Body Break Complete")
        XCTAssertEqual(L10n.tr("overlay.bodyBody"), "Stand up, breathe, and move.")
    }

    func testBodySkipHelpMatchesSkipAvailabilityInsteadOfPostponeState() {
        defer { L10n.languageOverride = nil }

        L10n.languageOverride = "en"
        XCTAssertEqual(L10n.tr("overlay.bodySkipHelp"), "Skip this Body Break when skipping is allowed.")
        XCTAssertFalse(L10n.tr("overlay.bodySkipHelp").localizedCaseInsensitiveContains("postpon"))

        L10n.languageOverride = "zh-Hans"
        XCTAssertEqual(L10n.tr("overlay.bodySkipHelp"), "在允许跳过时，跳过这次活动休息。")
        XCTAssertFalse(L10n.tr("overlay.bodySkipHelp").contains("推迟"))
    }

    func testSimplifiedChineseVisibleValuesAvoidUntranslatedCoreTerms() throws {
        let values = try simplifiedChineseLocalizedValues().joined(separator: "\n")

        for forbiddenTerm in ["Eye Gate", "Body Break", "Focus /", "Mac-first", "skip/postpone"] {
            XCTAssertFalse(values.contains(forbiddenTerm), "Unexpected untranslated term: \(forbiddenTerm)")
        }
    }

    func testSimplifiedChineseEmergencyCopyUsesExitInsteadOfOverride() throws {
        let values = try simplifiedChineseLocalizedValues().joined(separator: "\n")

        XCTAssertTrue(values.contains("紧急退出"))
        XCTAssertFalse(values.contains("紧急覆盖"))
    }

    func testEmergencyCopyNeverDescribesLongPressConfirmation() throws {
        let englishValues = try localizedValues(language: "en").joined(separator: "\n")
        let simplifiedChineseValues = try localizedValues(language: "zh-Hans").joined(separator: "\n")

        for forbiddenTerm in ["hold", "long press", "press and hold"] {
            XCTAssertFalse(
                englishValues.localizedCaseInsensitiveContains(forbiddenTerm),
                "Emergency Exit must stay a two-click/two-Esc flow, not: \(forbiddenTerm)"
            )
        }
        for forbiddenTerm in ["长按", "按住"] {
            XCTAssertFalse(
                simplifiedChineseValues.contains(forbiddenTerm),
                "紧急退出必须保持点两次/两次 Esc，而不是：\(forbiddenTerm)"
            )
        }
    }

    func testVisiblePreferenceCopyAvoidsImplementationTerms() throws {
        defer { L10n.languageOverride = nil }

        let simplifiedChineseValues = try localizedValues(language: "zh-Hans").joined(separator: "\n")
        let englishValues = try localizedValues(language: "en").joined(separator: "\n")
        let simplifiedChineseLines = simplifiedChineseValues.components(separatedBy: "\n")
        let englishLines = englishValues.components(separatedBy: "\n")

        XCTAssertFalse(simplifiedChineseValues.contains("语言覆盖"))
        XCTAssertFalse(simplifiedChineseValues.contains("结束当前活动休息"))
        XCTAssertFalse(simplifiedChineseValues.contains("结束当前休息"))
        XCTAssertFalse(simplifiedChineseValues.contains("可用等待"))
        XCTAssertFalse(simplifiedChineseValues.contains("暂停切换"))
        XCTAssertFalse(simplifiedChineseValues.contains("原始规则 JSON"))
        XCTAssertFalse(simplifiedChineseValues.contains("原始提示 JSON"))
        XCTAssertFalse(simplifiedChineseValues.contains("可阅读内容自定义"))
        XCTAssertFalse(simplifiedChineseValues.contains("不跳过"))
        XCTAssertFalse(simplifiedChineseValues.contains("复制调试信息"))
        XCTAssertFalse(simplifiedChineseValues.contains("调试面板"))
        XCTAssertFalse(simplifiedChineseValues.contains("ShouldRest 调试"))
        XCTAssertFalse(simplifiedChineseValues.contains("调试信息"))
        XCTAssertFalse(simplifiedChineseValues.contains("管理员："))
        XCTAssertFalse(simplifiedChineseValues.contains("身体休息"))
        XCTAssertFalse(simplifiedChineseLines.contains("名称"))
        XCTAssertFalse(simplifiedChineseValues.contains("匹配词"))
        XCTAssertFalse(simplifiedChineseLines.contains("模式"))
        XCTAssertFalse(simplifiedChineseLines.contains("添加规则"))
        XCTAssertFalse(simplifiedChineseLines.contains("更新规则"))
        XCTAssertFalse(simplifiedChineseLines.contains("当前规则"))
        XCTAssertFalse(simplifiedChineseValues.contains("专注 / 勿扰"))
        XCTAssertFalse(simplifiedChineseValues.contains("加入轮换"))
        XCTAssertFalse(simplifiedChineseValues.contains("更新轮换"))
        XCTAssertFalse(simplifiedChineseValues.contains("当前轮换"))
        XCTAssertFalse(simplifiedChineseValues.contains("立即护眼休息"))
        XCTAssertFalse(simplifiedChineseValues.contains("立即活动休息"))
        XCTAssertFalse(simplifiedChineseValues.contains("手动完成"))
        XCTAssertFalse(simplifiedChineseValues.contains("手动暂停"))
        XCTAssertFalse(simplifiedChineseValues.contains("睡眠或锁屏时暂停调度"))
        XCTAssertFalse(simplifiedChineseLines.contains("确认无限期暂停"))
        XCTAssertFalse(simplifiedChineseValues.contains("抵扣自然休息"))
        XCTAssertFalse(simplifiedChineseValues.contains("闲置"))
        XCTAssertFalse(simplifiedChineseValues.contains("空闲"))
        XCTAssertFalse(simplifiedChineseValues.contains("专注模式延后活动休息"))
        XCTAssertFalse(simplifiedChineseValues.contains("专注模式规则"))
        XCTAssertFalse(simplifiedChineseValues.contains("匹配时行为"))
        XCTAssertFalse(simplifiedChineseValues.contains("匹配时暂停"))
        XCTAssertFalse(simplifiedChineseValues.contains("仅在匹配时"))
        XCTAssertFalse(simplifiedChineseValues.contains("更新源地址"))
        XCTAssertFalse(simplifiedChineseValues.contains("暂停到早晨方式"))
        XCTAssertFalse(simplifiedChineseValues.contains("日出纬度"))
        XCTAssertFalse(simplifiedChineseValues.contains("日出经度"))
        XCTAssertFalse(simplifiedChineseValues.contains("批量编辑"))
        XCTAssertFalse(englishValues.contains("Language override"))
        XCTAssertFalse(englishLines.contains("Operations"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("bundle id"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("app identifier"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("com.apple"))
        XCTAssertFalse(simplifiedChineseValues.contains("应用标识"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("feed URL"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("update feed"))
        XCTAssertFalse(englishValues.contains("Pause until morning mode"))
        XCTAssertFalse(englishValues.contains("Resume hour"))
        XCTAssertFalse(englishValues.contains("Sunrise latitude"))
        XCTAssertFalse(englishValues.contains("Sunrise longitude"))
        XCTAssertFalse(englishValues.contains("Credit idle"))
        XCTAssertFalse(englishValues.contains("Credit natural rests"))
        XCTAssertFalse(englishValues.contains("Idle periods"))
        XCTAssertFalse(englishValues.contains("Idle time"))
        XCTAssertFalse(englishValues.contains("Focus mode defers Body Break"))
        XCTAssertFalse(englishValues.contains("Focus mode rules"))
        XCTAssertFalse(englishValues.contains("Focus / Do Not Disturb"))
        XCTAssertFalse(englishValues.contains("Matched app behavior"))
        XCTAssertFalse(englishValues.contains("while matched"))
        XCTAssertFalse(englishValues.contains("matched apps"))
        XCTAssertFalse(englishLines.contains("Name"))
        XCTAssertFalse(englishLines.contains("Match terms"))
        XCTAssertFalse(englishValues.contains("match terms"))
        XCTAssertFalse(englishLines.contains("Mode"))
        XCTAssertFalse(englishLines.contains("Add Rule"))
        XCTAssertFalse(englishLines.contains("Update Rule"))
        XCTAssertFalse(englishLines.contains("Current rules"))
        XCTAssertFalse(englishValues.contains("available after"))
        XCTAssertFalse(englishValues.contains("Body start sound"))
        XCTAssertFalse(englishValues.contains("Body finish sound"))
        XCTAssertFalse(englishValues.contains("Pause toggle"))
        XCTAssertFalse(englishValues.contains("Raw rule JSON"))
        XCTAssertFalse(englishValues.contains("Raw idea JSON"))
        XCTAssertFalse(englishValues.contains("App rules JSON"))
        XCTAssertFalse(englishValues.contains("Ideas JSON"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("json editor"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("json array"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("valid json"))
        XCTAssertFalse(englishValues.contains("Add import text before copying it."))
        XCTAssertFalse(englishValues.contains("Change the import text before restoring saved text."))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("raw rule json"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("raw idea json"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("bulk edit"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("readable content customization"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("noskip"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("current schedule kept"))
        XCTAssertFalse(englishValues.contains("Copy Debug Info"))
        XCTAssertFalse(englishValues.contains("Debug Panel"))
        XCTAssertFalse(englishValues.contains("ShouldRest Debug"))
        XCTAssertFalse(englishValues.contains("Debug Info"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("runtime flags"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("diagnostic snapshot"))
        XCTAssertFalse(englishValues.contains("Settings File"))
        XCTAssertFalse(englishValues.contains("Copy Settings Path"))
        XCTAssertFalse(englishValues.contains("Settings path copied"))
        XCTAssertFalse(englishValues.contains("Administrative controls"))
        XCTAssertFalse(englishValues.contains("Hide administrative controls"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("deployment policy"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("managed setups"))
        XCTAssertFalse(simplifiedChineseValues.contains("管理员控制"))
        XCTAssertFalse(simplifiedChineseValues.contains("部署策略"))
        XCTAssertFalse(simplifiedChineseValues.contains("托管部署"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("print settings path"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("print log path"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("settings path hidden"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("logs path hidden"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("hidden by admin"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("hidden by administrator"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("settings file path"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("app paths"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("support paths"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("app log file"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("settings file in finder"))
        XCTAssertFalse(englishValues.contains("Reveal Log"))
        XCTAssertFalse(englishValues.contains("Reveal Settings"))
        XCTAssertFalse(englishValues.contains("blocking the app"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("app exclusion"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("app exclusions"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("end active rest"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("deferred rest"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("scope rests"))
        XCTAssertFalse(englishValues.contains("Admin:"))
        XCTAssertFalse(englishValues.contains("debug, and preference"))
        XCTAssertFalse(englishValues.contains("Add to Rotation"))
        XCTAssertFalse(englishValues.contains("Update Rotation"))
        XCTAssertFalse(englishValues.contains("Current rotation"))
        XCTAssertFalse(englishValues.contains("Take Eye Gate Now"))
        XCTAssertFalse(englishValues.contains("Take Body Break Now"))
        XCTAssertFalse(englishValues.contains("Take Next Scheduled Rest Now"))
        XCTAssertFalse(englishValues.contains("Pause-until-morning mode"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("manual finish"))
        XCTAssertFalse(englishValues.contains("Manual pause"))
        XCTAssertFalse(englishValues.contains("Click Again to Pause Indefinitely"))
        XCTAssertFalse(englishValues.contains("Confirm Pause Indefinitely"))
        XCTAssertFalse(englishValues.contains("Next scheduled rest now"))
        XCTAssertFalse(englishValues.contains("Resume at hour"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("scheduler"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("danger indicator"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("danger score"))
        XCTAssertFalse(englishValues.contains("Eye Gate(s)"))
        XCTAssertFalse(englishValues.contains("%ds remaining"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("deadlock"))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("one-shot automation tasks"))
        XCTAssertFalse(englishValues.contains("Stretchly-compatible"))
        XCTAssertFalse(englishValues.contains("Frequent Eyes"))
        XCTAssertFalse(englishValues.contains("Learn More"))
        XCTAssertFalse(englishValues.contains("Use Selected"))
        XCTAssertFalse(englishValues.contains("..."))
        XCTAssertFalse(englishValues.localizedCaseInsensitiveContains("opaque"))
        XCTAssertFalse(simplifiedChineseValues.contains("恢复小时"))
        XCTAssertFalse(simplifiedChineseValues.contains("危险值"))
        XCTAssertFalse(simplifiedChineseValues.contains("锁死"))
        XCTAssertFalse(simplifiedChineseValues.contains("兼容 Stretchly"))
        XCTAssertFalse(simplifiedChineseValues.contains("Bundle ID"))
        XCTAssertFalse(simplifiedChineseValues.contains("运行时标记"))
        XCTAssertFalse(simplifiedChineseValues.contains("诊断快照"))
        XCTAssertFalse(simplifiedChineseValues.contains("设置路径"))
        XCTAssertFalse(simplifiedChineseValues.contains("应用路径"))
        XCTAssertFalse(simplifiedChineseValues.contains("支持路径"))
        XCTAssertFalse(simplifiedChineseValues.contains("应用日志文件"))
        XCTAssertFalse(simplifiedChineseValues.contains("显示设置文件"))
        XCTAssertFalse(simplifiedChineseValues.contains("路径访问"))
        XCTAssertFalse(simplifiedChineseValues.contains("阻塞应用"))
        XCTAssertFalse(simplifiedChineseValues.contains("应用排除"))
        XCTAssertFalse(simplifiedChineseValues.contains("限定休息生效范围"))
        XCTAssertFalse(simplifiedChineseValues.contains("JSON 编辑器"))
        XCTAssertFalse(simplifiedChineseValues.contains("有效 JSON"))
        XCTAssertFalse(simplifiedChineseValues.contains("先添加导入文本，才能复制。"))
        XCTAssertFalse(simplifiedChineseValues.contains("修改导入文本后才能还原已保存文本。"))
        XCTAssertFalse(simplifiedChineseValues.contains("一次性自动化任务"))
        XCTAssertFalse(simplifiedChineseValues.contains("再次点击确认无限期暂停"))
        XCTAssertFalse(simplifiedChineseValues.contains("立即执行下一项计划休息"))
        XCTAssertFalse(simplifiedChineseValues.contains("不透明"))
        XCTAssertFalse(simplifiedChineseValues.contains("..."))

        XCTAssertTrue(englishValues.contains("Body Break start sound"))
        XCTAssertTrue(englishValues.contains("Body Break finish sound"))
        XCTAssertTrue(englishValues.contains("App behavior"))
        XCTAssertTrue(englishValues.contains("Morning resume"))
        XCTAssertTrue(englishValues.contains("Pause until morning"))
        XCTAssertTrue(englishValues.contains("Pause or resume"))
        XCTAssertTrue(englishValues.contains("Finish Eye Gate or manage Body Break"))
        XCTAssertTrue(englishValues.contains("Manage Body Break"))
        XCTAssertTrue(englishValues.contains("delayed rest"))
        XCTAssertTrue(englishValues.contains("Indefinitely…"))
        XCTAssertTrue(englishValues.contains("Resume at"))
        XCTAssertTrue(englishValues.contains("Show rest debt indicator"))
        XCTAssertTrue(englishValues.contains("Debt %d/10"))
        XCTAssertFalse(englishValues.contains("Show rest pressure indicator"))
        XCTAssertFalse(englishValues.contains("Pressure %d/10"))
        XCTAssertTrue(englishValues.contains("Next Body Break after %d Eye Gates"))
        XCTAssertTrue(englishValues.contains("%@ active, %@ remaining"))
        XCTAssertTrue(englishValues.contains("Balanced"))
        XCTAssertTrue(englishValues.contains("More Eye Rests"))
        XCTAssertTrue(englishValues.contains("About ShouldRest"))
        XCTAssertTrue(englishValues.contains("Full-featured controls"))
        XCTAssertTrue(englishValues.contains("Emergency stays in the overlay"))
        XCTAssertTrue(englishValues.contains("Start With This Rhythm"))
        XCTAssertTrue(englishValues.contains("screen-covering 20-second Eye Gates"))
        XCTAssertTrue(englishValues.contains("Brief screen-covering rests"))
        XCTAssertTrue(englishValues.contains("Full-screen coverage keeps 20-second eye rests hard to ignore"))
        XCTAssertTrue(englishValues.contains("Add Idea"))
        XCTAssertTrue(englishValues.contains("Update Idea"))
        XCTAssertTrue(englishValues.contains("Custom ideas"))
        XCTAssertTrue(englishValues.contains("Rule name"))
        XCTAssertTrue(englishValues.contains("App Rules"))
        XCTAssertTrue(englishValues.contains("Enable app rules"))
        XCTAssertTrue(englishValues.contains("When these apps are active"))
        XCTAssertTrue(englishValues.contains("Pause rests during these apps"))
        XCTAssertTrue(englishValues.contains("Add App Rule"))
        XCTAssertTrue(englishValues.contains("Update App Rule"))
        XCTAssertTrue(englishValues.contains("Saved app rules"))
        XCTAssertTrue(englishValues.contains("App rules import text"))
        XCTAssertTrue(englishValues.contains("Import or Export App Rules"))
        XCTAssertTrue(englishValues.contains("Idea import text"))
        XCTAssertTrue(englishValues.contains("Import or Export Ideas"))
        XCTAssertTrue(englishValues.contains("Import text has an invalid format"))
        XCTAssertFalse(englishValues.contains("Open Advanced App Rule Editor"))
        XCTAssertFalse(englishValues.contains("Open Advanced Idea Editor"))
        XCTAssertTrue(englishValues.contains("Copy Support Report"))
        XCTAssertTrue(englishValues.contains("ShouldRest Support Report"))
        XCTAssertTrue(englishValues.contains("Support Report"))
        XCTAssertTrue(englishValues.contains("Copy the current rest state, settings summary, and troubleshooting details."))
        XCTAssertFalse(englishValues.contains("Copy Diagnostics"))
        XCTAssertFalse(englishValues.contains("ShouldRest Diagnostics"))
        XCTAssertTrue(englishValues.contains("ShouldRest is ready"))
        XCTAssertTrue(englishValues.contains("Start Eye Gate Now"))
        XCTAssertTrue(englishValues.contains("Start Body Break Now"))
        XCTAssertTrue(englishValues.contains("Start Next Rest Now"))
        XCTAssertTrue(englishValues.contains("Start next scheduled rest"))
        XCTAssertTrue(englishValues.contains("Start Eye Gate"))
        XCTAssertTrue(englishValues.contains("Start Body Break"))
        XCTAssertTrue(englishValues.contains("Set Shortcut"))
        XCTAssertTrue(englishValues.contains("Review Conflict"))
        XCTAssertNotEqual(L10n.tr("prefs.shortcutConflictReview"), "Show")
        XCTAssertTrue(englishValues.contains("queued commands"))
        XCTAssertTrue(simplifiedChineseValues.contains("应用行为"))
        XCTAssertTrue(simplifiedChineseValues.contains("早晨恢复"))
        XCTAssertTrue(simplifiedChineseValues.contains("暂停或恢复"))
        XCTAssertTrue(simplifiedChineseValues.contains("完成护眼休息或管理活动休息"))
        XCTAssertTrue(simplifiedChineseValues.contains("管理活动休息"))
        XCTAssertTrue(simplifiedChineseValues.contains("无限期暂停…"))
        XCTAssertTrue(simplifiedChineseValues.contains("恢复时间"))
        XCTAssertTrue(simplifiedChineseValues.contains("显示休息欠账指示器"))
        XCTAssertTrue(simplifiedChineseValues.contains("欠账 %d/10"))
        XCTAssertFalse(simplifiedChineseValues.contains("显示休息压力指示器"))
        XCTAssertFalse(simplifiedChineseValues.contains("压力 %d/10"))
        XCTAssertTrue(simplifiedChineseValues.contains("均衡"))
        XCTAssertTrue(simplifiedChineseValues.contains("更多护眼"))
        XCTAssertTrue(simplifiedChineseValues.contains("关于 ShouldRest"))
        XCTAssertTrue(simplifiedChineseValues.contains("完整控制能力"))
        XCTAssertTrue(simplifiedChineseValues.contains("覆盖层内紧急退出"))
        XCTAssertTrue(simplifiedChineseValues.contains("使用这个节奏开始"))
        XCTAssertTrue(simplifiedChineseValues.contains("覆盖屏幕的 20 秒护眼休息"))
        XCTAssertTrue(simplifiedChineseValues.contains("短暂覆盖屏幕的护眼休息"))
        XCTAssertTrue(simplifiedChineseValues.contains("覆盖屏幕让 20 秒护眼休息更难被忽视"))
        XCTAssertTrue(simplifiedChineseValues.contains("添加提示"))
        XCTAssertTrue(simplifiedChineseValues.contains("更新提示"))
        XCTAssertTrue(simplifiedChineseValues.contains("自定义提示"))
        XCTAssertTrue(simplifiedChineseValues.contains("规则名称"))
        XCTAssertTrue(simplifiedChineseValues.contains("应用规则"))
        XCTAssertTrue(simplifiedChineseValues.contains("这些应用运行时"))
        XCTAssertTrue(simplifiedChineseValues.contains("这些应用运行时暂停休息"))
        XCTAssertTrue(simplifiedChineseValues.contains("添加应用规则"))
        XCTAssertTrue(simplifiedChineseValues.contains("查看冲突"))
        XCTAssertFalse(simplifiedChineseValues.contains("定位"))
        XCTAssertTrue(simplifiedChineseValues.contains("更新应用规则"))
        XCTAssertTrue(simplifiedChineseValues.contains("已保存应用规则"))
        XCTAssertFalse(simplifiedChineseValues.contains("应用规则 JSON"))
        XCTAssertFalse(simplifiedChineseValues.contains("提示 JSON"))
        XCTAssertFalse(simplifiedChineseValues.contains("JSON 数组"))
        XCTAssertTrue(simplifiedChineseValues.contains("应用规则导入文本"))
        XCTAssertTrue(simplifiedChineseValues.contains("导入或导出应用规则"))
        XCTAssertTrue(simplifiedChineseValues.contains("提示导入文本"))
        XCTAssertTrue(simplifiedChineseValues.contains("导入或导出提示"))
        XCTAssertTrue(simplifiedChineseValues.contains("导入文本格式无效"))
        XCTAssertFalse(simplifiedChineseValues.contains("打开高级应用规则编辑器"))
        XCTAssertFalse(simplifiedChineseValues.contains("打开高级提示编辑器"))
        XCTAssertTrue(simplifiedChineseValues.contains("复制支持报告"))
        XCTAssertTrue(simplifiedChineseValues.contains("ShouldRest 支持报告"))
        XCTAssertTrue(simplifiedChineseValues.contains("支持报告"))
        XCTAssertTrue(simplifiedChineseValues.contains("复制当前休息状态、设置摘要和排查问题所需信息。"))
        XCTAssertFalse(simplifiedChineseValues.contains("复制诊断信息"))
        XCTAssertFalse(simplifiedChineseValues.contains("ShouldRest 诊断"))
        XCTAssertTrue(simplifiedChineseValues.contains("ShouldRest 已就绪"))
        XCTAssertTrue(simplifiedChineseValues.contains("立即开始护眼休息"))
        XCTAssertTrue(simplifiedChineseValues.contains("立即开始活动休息"))
        XCTAssertTrue(simplifiedChineseValues.contains("设置快捷键"))
        XCTAssertTrue(simplifiedChineseValues.contains("排队等待的命令"))
        XCTAssertFalse(simplifiedChineseValues.contains("待处理的自动化请求"))

        L10n.languageOverride = "en"
        XCTAssertEqual(L10n.tr("prefs.eyeGateNow"), "Start Eye Gate")
        XCTAssertEqual(L10n.tr("prefs.bodyBreakNow"), "Start Body Break")
        XCTAssertEqual(L10n.tr("prefs.nextScheduledRest"), "Start next scheduled rest")
        XCTAssertEqual(L10n.tr("shortcut.add"), "Set Shortcut")
        XCTAssertEqual(L10n.tr("prefs.activeRestShortcut.eyeAndBody"), "Finish Eye Gate or manage Body Break")
        XCTAssertEqual(L10n.tr("prefs.activeRestShortcut.body"), "Manage Body Break")
        XCTAssertEqual(L10n.tr("prefs.activeRestShortcut.eye"), "Finish Eye Gate")
        XCTAssertEqual(L10n.tr("prefs.naturalBreaks"), "Count time away as rest")
        XCTAssertEqual(L10n.tr("prefs.naturalIdleMinutes"), "Time away counts after")
        XCTAssertTrue(L10n.tr("prefs.naturalIdleMinutesHelp").contains("Time away must reach"))
        XCTAssertEqual(L10n.tr("prefs.monitorFocus"), "Detect Focus or Do Not Disturb")
        XCTAssertEqual(L10n.tr("prefs.focusDefersBody"), "Delay Body Break during Focus")
        XCTAssertEqual(L10n.tr("prefs.contextSummary.focusDefersBody"), "Focus delays Body Break.")
        XCTAssertEqual(L10n.tr("prefs.name"), "Rule name")
        XCTAssertEqual(L10n.tr("prefs.matchTerms"), "Apps")
        XCTAssertEqual(L10n.tr("prefs.matchTermsPlaceholder"), "Zoom or Keynote")
        XCTAssertTrue(L10n.tr("prefs.appExclusionTermsHelp").contains("Choose Add Running App"))
        XCTAssertTrue(L10n.tr("prefs.appExclusionTermsHelp").contains("If the app is not running"))
        XCTAssertFalse(L10n.tr("prefs.appExclusionTermsHelp").localizedCaseInsensitiveContains("app identifier"))
        XCTAssertFalse(L10n.tr("prefs.appExclusionTermsHelp").localizedCaseInsensitiveContains("com.apple"))
        XCTAssertTrue(L10n.tr("prefs.contextSummary.appRulesOne").contains("limit rests to those apps"))
        XCTAssertTrue(L10n.tr("prefs.enablePrimaryExclusionHelp").contains("while those apps are active"))
        XCTAssertEqual(L10n.tr("prefs.mode"), "When these apps are active")
        XCTAssertEqual(L10n.tr("prefs.addAppExclusionRule"), "Add App Rule")
        XCTAssertEqual(L10n.tr("prefs.updateAppExclusionRule"), "Update App Rule")
        XCTAssertEqual(L10n.tr("prefs.cancelAppExclusionRuleEdit"), "Cancel Edit")
        XCTAssertEqual(L10n.tr("prefs.appExclusionRules"), "Saved app rules")
        XCTAssertEqual(L10n.tr("prefs.sectionExclusion"), "App Rules")
        XCTAssertEqual(L10n.tr("prefs.enablePrimaryExclusion"), "Enable app rules")
        XCTAssertEqual(L10n.tr("prefs.advancedRulesJSON"), "App rules import text")
        XCTAssertEqual(L10n.tr("prefs.showAdvancedRules"), "Import or Export App Rules")
        XCTAssertEqual(L10n.tr("prefs.copyBulkEditor"), "Copy Import Text")
        XCTAssertEqual(L10n.tr("prefs.restoreBulkEditor"), "Restore Saved Text")
        XCTAssertEqual(L10n.tr("prefs.copyAppRulesBulkEditor"), "Copy App Rules Text")
        XCTAssertEqual(L10n.tr("prefs.restoreAppRulesBulkEditor"), "Restore App Rules Text")
        XCTAssertEqual(L10n.tr("prefs.copyAppRulesBulkEditorDisabledEmptyHelp"), "Add app-rule import text before copying it.")
        XCTAssertEqual(
            L10n.tr("prefs.restoreAppRulesBulkEditorDisabledNoChangesHelp"),
            "Change the app-rule import text before restoring saved app rules."
        )
        XCTAssertEqual(L10n.tr("prefs.advancedIdeasJSON"), "Idea import text")
        XCTAssertEqual(L10n.tr("prefs.showAdvancedIdeas"), "Import or Export Ideas")
        XCTAssertEqual(L10n.tr("prefs.copyIdeasBulkEditor"), "Copy Idea Text")
        XCTAssertEqual(L10n.tr("prefs.restoreIdeasBulkEditor"), "Restore Idea Text")
        XCTAssertEqual(L10n.tr("prefs.copyIdeasBulkEditorDisabledEmptyHelp"), "Add idea import text before copying it.")
        XCTAssertEqual(
            L10n.tr("prefs.restoreIdeasBulkEditorDisabledNoChangesHelp"),
            "Change the idea import text before restoring saved custom ideas."
        )
        XCTAssertEqual(L10n.tr("prefs.invalidJSONTitle"), "Import text has an invalid format")
        XCTAssertEqual(
            L10n.format("prefs.invalidJSONBody", "App rules import text", "Missing bracket"),
            "Fix App rules import text before settings can save. Details: Missing bracket"
        )
        XCTAssertEqual(L10n.tr("prefs.previewSound"), "Play Preview")
        XCTAssertEqual(L10n.tr("prefs.cancelCustomIdeaEdit"), "Cancel Edit")
        XCTAssertEqual(L10n.tr("prefs.sectionOperations"), "App behavior")
        XCTAssertEqual(L10n.tr("prefs.pauseUntilMorningMode"), "Morning resume")
        XCTAssertEqual(L10n.tr("prefs.pauseUntilMorningHour"), "Resume at")
        XCTAssertEqual(L10n.tr("prefs.pauseUntilMorningLocation"), "Use sunrise for")
        XCTAssertEqual(L10n.tr("prefs.pauseUntilMorningLatitude"), "Custom latitude")
        XCTAssertEqual(L10n.tr("prefs.pauseUntilMorningLongitude"), "Custom longitude")
        XCTAssertEqual(L10n.tr("prefs.morningMode.hour"), "Fixed time")
        XCTAssertEqual(L10n.tr("prefs.morningMode.sunrise"), "Sunrise")
        XCTAssertEqual(L10n.tr("prefs.updateFeedURL"), "Update source")
        XCTAssertTrue(L10n.tr("prefs.updateFeedURLHelp").contains("looks for new releases"))
        XCTAssertEqual(L10n.tr("notification.updateNoFeed"), "No update source is configured.")
        XCTAssertEqual(L10n.tr("prefs.adminHideUpdates"), "Hide update UI")
        XCTAssertEqual(L10n.tr("prefs.adminHideSettingsPath"), "Hide file locations")
        XCTAssertEqual(L10n.tr("prefs.adminHideStrict"), "Hide strict preferences")
        XCTAssertEqual(L10n.tr("prefs.preferencesMessage"), "Preferences banner")
        XCTAssertTrue(L10n.tr("prefs.preferencesMessageHelp").contains("top of Preferences"))
        XCTAssertEqual(L10n.tr("prefs.showAdminControls"), "Advanced support controls")
        XCTAssertEqual(L10n.tr("prefs.hideAdminControls"), "Hide advanced support controls")
        XCTAssertTrue(L10n.tr("prefs.adminControlsHelp").contains("rarely changed support options"))
        XCTAssertEqual(L10n.tr("prefs.chooseFile"), "Choose Image…")
        XCTAssertEqual(L10n.tr("prefs.clear"), "Clear Image")
        XCTAssertEqual(L10n.tr("prefs.imagePreviewEmpty"), "Drop or choose an image")
        XCTAssertEqual(L10n.tr("prefs.noImageSelected"), "Drop or choose an image")
        XCTAssertEqual(L10n.tr("prefs.eyeManualFinish"), "Wait for me after Eye Gate ends")
        XCTAssertEqual(L10n.tr("prefs.manualFinish"), "Wait for me after Body Break ends")
        XCTAssertEqual(L10n.tr("status.pauseReason.user"), "Paused by you")
        XCTAssertTrue(L10n.tr("prefs.eyeManualFinishHelp").contains("Early dismissal stays disabled"))
        XCTAssertTrue(L10n.tr("prefs.bodyManualFinishHelp").contains("instead of closing immediately"))
        XCTAssertEqual(L10n.tr("menu.copyDebug"), "Copy Support Report")
        XCTAssertEqual(L10n.tr("menu.debugPanel"), "Support Report…")
        XCTAssertEqual(L10n.tr("debug.title"), "ShouldRest Support Report")
        XCTAssertEqual(L10n.tr("debug.copy"), "Copy Report")
        XCTAssertEqual(L10n.tr("debug.refresh"), "Refresh Report")
        XCTAssertTrue(L10n.tr("debug.textHelp").contains("Copy Report"))
        XCTAssertEqual(L10n.tr("debug.ready"), "Report ready")
        XCTAssertEqual(L10n.tr("debug.copied"), "Copied to Clipboard")
        XCTAssertEqual(L10n.tr("debug.updated"), "Report refreshed")
        XCTAssertEqual(L10n.tr("debug.openLog"), "Show Log in Finder")
        XCTAssertEqual(L10n.tr("debug.openSettings"), "Show Settings in Finder")
        XCTAssertTrue(L10n.tr("debug.summaryEyeActiveBody").localizedCaseInsensitiveContains("Emergency Exit twice"))
        XCTAssertTrue(L10n.tr("debug.summaryEyeActiveBody").localizedCaseInsensitiveContains("Esc twice"))
        XCTAssertFalse(L10n.tr("debug.summaryEyeActiveBody").localizedCaseInsensitiveContains("Esc once"))
        XCTAssertEqual(L10n.tr("about.debug"), "Support Report")
        XCTAssertEqual(L10n.tr("about.compatibilityTitle"), "Full-featured controls")
        XCTAssertTrue(L10n.tr("menu.resetHelp").contains("queued commands"))
        XCTAssertTrue(L10n.tr("prefs.resetShortcutHelp").contains("queued commands"))
        XCTAssertTrue(L10n.tr("reset.confirmBody").contains("delayed rests"))
        XCTAssertTrue(L10n.tr("reset.confirmBody").contains("queued commands"))
        XCTAssertFalse(L10n.tr("menu.resetHelp").localizedCaseInsensitiveContains("pending automation"))
        XCTAssertFalse(L10n.tr("prefs.resetShortcutHelp").localizedCaseInsensitiveContains("pending automation"))
        XCTAssertFalse(L10n.tr("reset.confirmBody").localizedCaseInsensitiveContains("pending automation"))
        XCTAssertFalse(L10n.tr("reset.confirmBody").localizedCaseInsensitiveContains("pause state"))
        XCTAssertFalse(L10n.tr("reset.confirmBody").localizedCaseInsensitiveContains("deferred rest"))
        XCTAssertFalse(L10n.tr("reset.confirmBody").localizedCaseInsensitiveContains("one-shot automation tasks"))
        XCTAssertNotEqual(L10n.tr("prefs.imagePreviewEmpty"), "No image selected")
        XCTAssertNotEqual(L10n.tr("prefs.chooseFile"), "Choose…")
        XCTAssertNotEqual(L10n.tr("prefs.clear"), "Clear")
        XCTAssertNotEqual(L10n.tr("prefs.cancelAppExclusionRuleEdit"), "Cancel")
        XCTAssertNotEqual(L10n.tr("prefs.cancelCustomIdeaEdit"), "Cancel")
        XCTAssertNotEqual(L10n.tr("prefs.previewSound"), "Preview")
        XCTAssertNotEqual(L10n.tr("prefs.eyeManualFinish"), "Manual finish after Eye Gate duration")
        XCTAssertNotEqual(L10n.tr("prefs.manualFinish"), "Manual finish after Body Break duration")
        XCTAssertNotEqual(L10n.tr("prefs.eyeGateNow"), "Eye Gate now")
        XCTAssertNotEqual(L10n.tr("prefs.bodyBreakNow"), "Body Break now")

        L10n.languageOverride = "zh-Hans"
        XCTAssertEqual(L10n.tr("prefs.eyeGateNow"), "立即开始护眼休息")
        XCTAssertEqual(L10n.tr("prefs.bodyBreakNow"), "立即开始活动休息")
        XCTAssertEqual(L10n.tr("prefs.nextScheduledRest"), "立即开始下一项计划休息")
        XCTAssertEqual(L10n.tr("shortcut.add"), "设置快捷键")
        XCTAssertEqual(L10n.tr("prefs.activeRestShortcut.eyeAndBody"), "完成护眼休息或管理活动休息")
        XCTAssertEqual(L10n.tr("prefs.activeRestShortcut.body"), "管理活动休息")
        XCTAssertEqual(L10n.tr("prefs.activeRestShortcut.eye"), "完成护眼休息")
        XCTAssertEqual(L10n.tr("prefs.naturalBreaks"), "离开 Mac 可计为休息")
        XCTAssertEqual(L10n.tr("prefs.naturalIdleMinutes"), "离开多久后计入")
        XCTAssertTrue(L10n.tr("prefs.naturalIdleMinutesHelp").contains("离开 Mac 达到这个时长"))
        XCTAssertEqual(L10n.tr("prefs.monitorFocus"), "识别专注或勿扰模式")
        XCTAssertEqual(L10n.tr("prefs.focusDefersBody"), "专注时延后活动休息")
        XCTAssertEqual(L10n.tr("prefs.contextSummary.focusDefersBody"), "专注时会延后活动休息。")
        XCTAssertEqual(L10n.tr("prefs.name"), "规则名称")
        XCTAssertEqual(L10n.tr("prefs.matchTerms"), "应用")
        XCTAssertEqual(L10n.tr("prefs.matchTermsPlaceholder"), "Zoom 或 Keynote")
        XCTAssertTrue(L10n.tr("prefs.appExclusionTermsHelp").contains("添加运行中应用"))
        XCTAssertTrue(L10n.tr("prefs.appExclusionTermsHelp").contains("如果应用没有运行"))
        XCTAssertFalse(L10n.tr("prefs.appExclusionTermsHelp").contains("应用标识"))
        XCTAssertFalse(L10n.tr("prefs.appExclusionTermsHelp").contains("com.apple"))
        XCTAssertTrue(L10n.tr("prefs.contextSummary.appRulesOne").contains("只在这些应用运行时安排休息"))
        XCTAssertTrue(L10n.tr("prefs.enablePrimaryExclusionHelp").contains("只在这些应用运行时生效"))
        XCTAssertEqual(L10n.tr("prefs.mode"), "这些应用运行时")
        XCTAssertEqual(L10n.tr("prefs.addAppExclusionRule"), "添加应用规则")
        XCTAssertEqual(L10n.tr("prefs.updateAppExclusionRule"), "更新应用规则")
        XCTAssertEqual(L10n.tr("prefs.cancelAppExclusionRuleEdit"), "取消编辑")
        XCTAssertEqual(L10n.tr("prefs.appExclusionRules"), "已保存应用规则")
        XCTAssertEqual(L10n.tr("prefs.sectionExclusion"), "应用规则")
        XCTAssertEqual(L10n.tr("prefs.enablePrimaryExclusion"), "启用应用规则")
        XCTAssertEqual(L10n.tr("prefs.advancedRulesJSON"), "应用规则导入文本")
        XCTAssertEqual(L10n.tr("prefs.showAdvancedRules"), "导入或导出应用规则")
        XCTAssertEqual(L10n.tr("prefs.copyBulkEditor"), "复制导入文本")
        XCTAssertEqual(L10n.tr("prefs.restoreBulkEditor"), "还原已保存文本")
        XCTAssertEqual(L10n.tr("prefs.copyAppRulesBulkEditor"), "复制应用规则文本")
        XCTAssertEqual(L10n.tr("prefs.restoreAppRulesBulkEditor"), "还原应用规则文本")
        XCTAssertEqual(L10n.tr("prefs.copyAppRulesBulkEditorDisabledEmptyHelp"), "先添加应用规则导入文本，才能复制。")
        XCTAssertEqual(
            L10n.tr("prefs.restoreAppRulesBulkEditorDisabledNoChangesHelp"),
            "修改应用规则导入文本后，才能还原已保存应用规则。"
        )
        XCTAssertEqual(L10n.tr("prefs.advancedIdeasJSON"), "提示导入文本")
        XCTAssertEqual(L10n.tr("prefs.showAdvancedIdeas"), "导入或导出提示")
        XCTAssertEqual(L10n.tr("prefs.copyIdeasBulkEditor"), "复制提示文本")
        XCTAssertEqual(L10n.tr("prefs.restoreIdeasBulkEditor"), "还原提示文本")
        XCTAssertEqual(L10n.tr("prefs.copyIdeasBulkEditorDisabledEmptyHelp"), "先添加提示导入文本，才能复制。")
        XCTAssertEqual(
            L10n.tr("prefs.restoreIdeasBulkEditorDisabledNoChangesHelp"),
            "修改提示导入文本后，才能还原已保存自定义提示。"
        )
        XCTAssertEqual(L10n.tr("prefs.invalidJSONTitle"), "导入文本格式无效")
        XCTAssertEqual(
            L10n.format("prefs.invalidJSONBody", "应用规则导入文本", "缺少括号"),
            "请先修正应用规则导入文本，才能继续保存。详情：缺少括号"
        )
        XCTAssertEqual(L10n.tr("prefs.cancelCustomIdeaEdit"), "取消编辑")
        XCTAssertEqual(L10n.tr("prefs.sectionOperations"), "应用行为")
        XCTAssertEqual(L10n.tr("prefs.pauseUntilMorningMode"), "早晨恢复")
        XCTAssertEqual(L10n.tr("prefs.pauseUntilMorningHour"), "恢复时间")
        XCTAssertEqual(L10n.tr("prefs.pauseUntilMorningLocation"), "日出城市")
        XCTAssertEqual(L10n.tr("prefs.pauseUntilMorningLatitude"), "自定义纬度")
        XCTAssertEqual(L10n.tr("prefs.pauseUntilMorningLongitude"), "自定义经度")
        XCTAssertEqual(L10n.tr("prefs.morningMode.hour"), "固定时间")
        XCTAssertEqual(L10n.tr("prefs.morningMode.sunrise"), "日出时间")
        XCTAssertEqual(L10n.tr("prefs.updateFeedURL"), "更新来源")
        XCTAssertTrue(L10n.tr("prefs.updateFeedURLHelp").contains("查找新版本"))
        XCTAssertEqual(L10n.tr("prefs.chooseFile"), "选择图片…")
        XCTAssertEqual(L10n.tr("prefs.clear"), "清空图片")
        XCTAssertEqual(L10n.tr("prefs.previewSound"), "播放试听")
        XCTAssertEqual(L10n.tr("notification.updateNoFeed"), "未配置更新来源。")
        XCTAssertEqual(L10n.tr("prefs.adminHideUpdates"), "隐藏更新界面")
        XCTAssertEqual(L10n.tr("prefs.adminHideSettingsPath"), "隐藏文件位置")
        XCTAssertEqual(L10n.tr("prefs.adminHideStrict"), "隐藏严格模式偏好")
        XCTAssertEqual(L10n.tr("prefs.preferencesMessage"), "偏好窗口提示")
        XCTAssertTrue(L10n.tr("prefs.preferencesMessageHelp").contains("偏好窗口顶部"))
        XCTAssertEqual(L10n.tr("prefs.showAdminControls"), "高级支持选项")
        XCTAssertEqual(L10n.tr("prefs.hideAdminControls"), "隐藏高级支持选项")
        XCTAssertTrue(L10n.tr("prefs.adminControlsHelp").contains("很少改动的支持选项"))
        XCTAssertEqual(L10n.tr("prefs.imagePreviewEmpty"), "拖入或选择图片")
        XCTAssertEqual(L10n.tr("prefs.noImageSelected"), "拖入或选择图片")
        XCTAssertEqual(L10n.tr("prefs.eyeManualFinish"), "护眼休息计时结束后等我完成")
        XCTAssertEqual(L10n.tr("prefs.manualFinish"), "活动休息计时结束后等我完成")
        XCTAssertEqual(L10n.tr("status.pauseReason.user"), "你已暂停")
        XCTAssertTrue(L10n.tr("prefs.eyeManualFinishHelp").contains("仍然不能提前结束"))
        XCTAssertTrue(L10n.tr("prefs.bodyManualFinishHelp").contains("不是立即关闭"))
        XCTAssertEqual(L10n.tr("menu.copyDebug"), "复制支持报告")
        XCTAssertEqual(L10n.tr("menu.debugPanel"), "支持报告…")
        XCTAssertEqual(L10n.tr("menu.settingsFile"), "设置位置")
        XCTAssertEqual(L10n.tr("menu.copySettingsPath"), "复制位置")
        XCTAssertEqual(L10n.tr("menu.copySettingsPathDone"), "设置位置已复制到剪贴板。")
        XCTAssertEqual(L10n.tr("debug.title"), "ShouldRest 支持报告")
        XCTAssertEqual(L10n.tr("debug.copy"), "复制报告")
        XCTAssertEqual(L10n.tr("debug.refresh"), "刷新报告")
        XCTAssertTrue(L10n.tr("debug.textHelp").contains("复制报告"))
        XCTAssertEqual(L10n.tr("debug.ready"), "报告就绪")
        XCTAssertEqual(L10n.tr("debug.copied"), "已复制到剪贴板")
        XCTAssertEqual(L10n.tr("debug.updated"), "报告已刷新")
        XCTAssertEqual(L10n.tr("debug.openLog"), "在 Finder 中显示日志")
        XCTAssertEqual(L10n.tr("debug.openSettings"), "在 Finder 中显示设置")
        XCTAssertTrue(L10n.tr("debug.summaryEyeActiveBody").contains("紧急退出两次"))
        XCTAssertTrue(L10n.tr("debug.summaryEyeActiveBody").contains("两次 Esc"))
        XCTAssertFalse(L10n.tr("debug.summaryEyeActiveBody").contains("按一次 Esc"))
        XCTAssertEqual(L10n.tr("about.debug"), "支持报告")
        XCTAssertEqual(L10n.tr("about.compatibilityTitle"), "完整控制能力")
        XCTAssertTrue(L10n.tr("menu.resetHelp").contains("排队等待的命令"))
        XCTAssertTrue(L10n.tr("prefs.resetShortcutHelp").contains("排队等待的命令"))
        XCTAssertTrue(L10n.tr("reset.confirmBody").contains("排队等待的命令"))
        XCTAssertFalse(L10n.tr("menu.resetHelp").contains("待处理的自动化请求"))
        XCTAssertFalse(L10n.tr("prefs.resetShortcutHelp").contains("待处理的自动化请求"))
        XCTAssertFalse(L10n.tr("reset.confirmBody").contains("待处理的自动化请求"))
        XCTAssertFalse(L10n.tr("reset.confirmBody").contains("暂停状态"))
        XCTAssertFalse(L10n.tr("reset.confirmBody").contains("一次性自动化任务"))
        XCTAssertNotEqual(L10n.tr("prefs.imagePreviewEmpty"), "未选择图片")
        XCTAssertNotEqual(L10n.tr("prefs.previewSound"), "试听")
        XCTAssertNotEqual(L10n.tr("prefs.eyeManualFinish"), "护眼休息到时后手动完成")
        XCTAssertNotEqual(L10n.tr("prefs.manualFinish"), "活动休息到时后手动完成")
        L10n.languageOverride = nil
    }

    func testEmergencyCopyUsesInternalConfirmationWithoutCountdownOrExternalWindow() {
        defer { L10n.languageOverride = nil }

        L10n.languageOverride = "en"
        XCTAssertEqual(L10n.tr("overlay.emergencyOverride"), "Emergency Exit · Esc")
        XCTAssertEqual(L10n.tr("overlay.emergencyOverrideConfirm"), "Click again · Esc again")
        XCTAssertEqual(L10n.tr("overlay.emergencyOverrideArmed"), "Click again · Esc again")
        XCTAssertTrue(L10n.tr("overlay.emergencyOverrideConfirm").contains("Esc"))
        XCTAssertTrue(L10n.tr("overlay.emergencyOverrideHelp").contains("inside the overlay"))
        XCTAssertTrue(L10n.tr("prefs.eyeEmergencyOverrideHelp").contains("inside the overlay"))
        XCTAssertTrue(L10n.tr("prefs.eyeEmergencyOverrideHelp").localizedCaseInsensitiveContains("second click"))
        XCTAssertFalse(L10n.tr("prefs.eyeEmergencyOverrideHelp").localizedCaseInsensitiveContains("arm"))
        XCTAssertFalse(L10n.tr("prefs.eyeEmergencyOverrideHelp").localizedCaseInsensitiveContains("hold"))
        XCTAssertFalse(L10n.tr("prefs.eyeEmergencyOverrideHelp").localizedCaseInsensitiveContains("another window"))
        XCTAssertTrue(L10n.tr("menu.emergencyOverrideHelp").localizedCaseInsensitiveContains("two clicks"))
        XCTAssertFalse(L10n.tr("menu.emergencyOverrideHelp").localizedCaseInsensitiveContains("arm"))
        XCTAssertTrue(L10n.tr("cli.help").contains("eye|mini [-w wait]           Start Eye Gate now or after wait; it is always strict and text-free."))
        XCTAssertTrue(L10n.tr("cli.help").contains("Bring the active Eye Gate overlay forward for Emergency Exit."))
        XCTAssertTrue(L10n.tr("cli.help").contains("Open ShouldRest preferences."))
        XCTAssertTrue(L10n.tr("cli.help").contains("support                      Copy support report."))
        XCTAssertTrue(L10n.tr("cli.help").contains("support-panel                Open the support report window."))
        XCTAssertTrue(L10n.tr("cli.help").contains("Open the About window."))
        XCTAssertTrue(L10n.tr("cli.help").contains("url shouldrest://<command>    Run a shouldrest:// command."))
        XCTAssertTrue(L10n.tr("cli.help").contains("settings                     Show settings location."))
        XCTAssertTrue(L10n.tr("cli.help").contains("logs                         Show log location."))
        XCTAssertEqual(L10n.tr("cli.settingsPathHidden"), "Settings location is hidden in this setup.")
        XCTAssertEqual(L10n.tr("cli.logsPathHidden"), "Log location is hidden in this setup.")
        XCTAssertEqual(L10n.tr("cli.requestedAutomationURL"), "Requested shouldrest:// command: %@")
        XCTAssertEqual(L10n.tr("cli.requestedDiagnostics"), "Requested support report copy.")
        XCTAssertEqual(L10n.tr("cli.requestedDiagnosticsWindow"), "Requested support report window.")
        XCTAssertEqual(L10n.tr("cli.requestedAbout"), "Requested About window.")
        XCTAssertTrue(L10n.tr("cli.requestedEmergency").contains("inside the overlay"))
        XCTAssertTrue(L10n.tr("cli.requestedEmergency").localizedCaseInsensitiveContains("two clicks"))
        XCTAssertFalse(L10n.tr("cli.requestedEmergency").localizedCaseInsensitiveContains("another window"))
        XCTAssertFalse(L10n.tr("cli.requestedEmergency").localizedCaseInsensitiveContains("hold"))
        XCTAssertFalse(L10n.tr("cli.help").contains("eye|mini [-w wait] [-n]"))
        XCTAssertFalse(L10n.tr("cli.help").localizedCaseInsensitiveContains("url-style automation"))
        XCTAssertFalse(L10n.tr("cli.help").localizedCaseInsensitiveContains("automation URL"))
        XCTAssertFalse(L10n.tr("cli.help").localizedCaseInsensitiveContains("readable content is not customizable"))
        XCTAssertFalse(L10n.tr("cli.help").localizedCaseInsensitiveContains("running app"))
        XCTAssertFalse(L10n.tr("cli.help").localizedCaseInsensitiveContains("settings path"))
        XCTAssertFalse(L10n.tr("cli.help").localizedCaseInsensitiveContains("log path"))
        XCTAssertFalse(L10n.tr("cli.help").localizedCaseInsensitiveContains("hidden by policy"))
        XCTAssertFalse(L10n.tr("cli.settingsPathHidden").localizedCaseInsensitiveContains("policy"))
        XCTAssertFalse(L10n.tr("cli.logsPathHidden").localizedCaseInsensitiveContains("policy"))
        XCTAssertFalse(L10n.tr("cli.help").localizedCaseInsensitiveContains("hidden by admin"))
        XCTAssertFalse(L10n.tr("cli.help").contains("debug                        Copy support report."))
        XCTAssertFalse(L10n.tr("cli.help").contains("debug-panel"))
        XCTAssertFalse(L10n.tr("cli.help").localizedCaseInsensitiveContains("run it again"))
        XCTAssertTrue(L10n.tr("onboarding.emergencyFeatureBody").contains("external requests only bring it forward"))
        XCTAssertTrue(L10n.tr("onboarding.emergencyFeatureBody").localizedCaseInsensitiveContains("two clicks"))
        XCTAssertFalse(L10n.tr("onboarding.emergencyFeatureBody").localizedCaseInsensitiveContains("countdown"))
        XCTAssertTrue(L10n.tr("onboarding.emergencyFeatureBody").localizedCaseInsensitiveContains("without asking you to click another window"))

        L10n.languageOverride = "zh-Hans"
        XCTAssertEqual(L10n.tr("overlay.emergencyOverride"), "紧急退出 · Esc")
        XCTAssertEqual(L10n.tr("overlay.emergencyOverrideConfirm"), "再点一次 · 再按 Esc")
        XCTAssertEqual(L10n.tr("overlay.emergencyOverrideArmed"), "再点一次 · 再按 Esc")
        XCTAssertTrue(L10n.tr("overlay.emergencyOverrideConfirm").contains("Esc"))
        XCTAssertTrue(L10n.tr("overlay.emergencyOverrideHelp").contains("覆盖层内"))
        XCTAssertTrue(L10n.tr("prefs.eyeEmergencyOverrideHelp").contains("覆盖层内"))
        XCTAssertTrue(L10n.tr("prefs.eyeEmergencyOverrideHelp").contains("第二次点击"))
        XCTAssertFalse(L10n.tr("prefs.eyeEmergencyOverrideHelp").contains("待确认"))
        XCTAssertFalse(L10n.tr("prefs.eyeEmergencyOverrideHelp").contains("长按"))
        XCTAssertFalse(L10n.tr("prefs.eyeEmergencyOverrideHelp").contains("按住"))
        XCTAssertFalse(L10n.tr("prefs.eyeEmergencyOverrideHelp").contains("另一个窗口"))
        XCTAssertTrue(L10n.tr("menu.emergencyOverrideHelp").contains("点两次"))
        XCTAssertFalse(L10n.tr("menu.emergencyOverrideHelp").contains("待确认"))
        XCTAssertTrue(L10n.tr("cli.help").contains("eye|mini [-w wait]           立即或延迟开始护眼休息；始终严格且不显示自定义文字。"))
        XCTAssertTrue(L10n.tr("cli.help").contains("把当前护眼覆盖层带到前台以便紧急退出"))
        XCTAssertTrue(L10n.tr("cli.help").contains("打开偏好设置"))
        XCTAssertTrue(L10n.tr("cli.help").contains("support                      复制支持报告"))
        XCTAssertTrue(L10n.tr("cli.help").contains("support-panel                打开支持报告窗口"))
        XCTAssertTrue(L10n.tr("cli.help").contains("打开关于窗口"))
        XCTAssertTrue(L10n.tr("cli.help").contains("url shouldrest://<command>    执行 shouldrest:// 命令。"))
        XCTAssertTrue(L10n.tr("cli.help").contains("settings                     显示设置位置。"))
        XCTAssertTrue(L10n.tr("cli.help").contains("logs                         显示日志位置。"))
        XCTAssertEqual(L10n.tr("cli.settingsPathHidden"), "当前设置已隐藏设置位置。")
        XCTAssertEqual(L10n.tr("cli.logsPathHidden"), "当前设置已隐藏日志位置。")
        XCTAssertEqual(L10n.tr("cli.requestedAutomationURL"), "已请求执行 shouldrest:// 命令：%@")
        XCTAssertEqual(L10n.tr("cli.requestedDiagnostics"), "已请求复制支持报告。")
        XCTAssertEqual(L10n.tr("cli.requestedDiagnosticsWindow"), "已请求打开支持报告窗口。")
        XCTAssertEqual(L10n.tr("cli.requestedAbout"), "已请求打开关于窗口。")
        XCTAssertTrue(L10n.tr("cli.requestedEmergency").contains("覆盖层内"))
        XCTAssertTrue(L10n.tr("cli.requestedEmergency").contains("点两次"))
        XCTAssertFalse(L10n.tr("cli.requestedEmergency").contains("另一个窗口"))
        XCTAssertFalse(L10n.tr("cli.requestedEmergency").contains("长按"))
        XCTAssertFalse(L10n.tr("cli.help").contains("eye|mini [-w wait] [-n]"))
        XCTAssertFalse(L10n.tr("cli.help").contains("URL 风格自动化"))
        XCTAssertFalse(L10n.tr("cli.help").contains("debug                        复制支持报告"))
        XCTAssertFalse(L10n.tr("cli.help").contains("debug-panel"))
        XCTAssertFalse(L10n.tr("cli.requestedAutomationURL").contains("自动化 URL"))
        XCTAssertFalse(L10n.tr("cli.help").contains("可阅读内容"))
        XCTAssertFalse(L10n.tr("cli.help").contains("运行中 app"))
        XCTAssertFalse(L10n.tr("cli.help").contains("设置文件路径"))
        XCTAssertFalse(L10n.tr("cli.help").contains("日志路径"))
        XCTAssertFalse(L10n.tr("cli.help").contains("除非策略隐藏"))
        XCTAssertFalse(L10n.tr("cli.settingsPathHidden").contains("策略"))
        XCTAssertFalse(L10n.tr("cli.logsPathHidden").contains("策略"))
        XCTAssertFalse(L10n.tr("cli.help").contains("管理员"))
        XCTAssertFalse(L10n.tr("cli.help").contains("再次运行"))
        XCTAssertTrue(L10n.tr("onboarding.emergencyFeatureBody").contains("外部请求只会把覆盖层带到前台"))
        XCTAssertTrue(L10n.tr("onboarding.emergencyFeatureBody").contains("点两次"))
        XCTAssertFalse(L10n.tr("onboarding.emergencyFeatureBody").contains("倒计时"))
        XCTAssertTrue(L10n.tr("onboarding.emergencyFeatureBody").contains("不再要求你点击另一个窗口"))
    }

    func testOnboardingPrimaryActionNamesSelectedRhythm() {
        defer { L10n.languageOverride = nil }

        L10n.languageOverride = "en"
        XCTAssertEqual(
            L10n.format("onboarding.useSelectedWithPreset", "More Eye Rests"),
            "Start With More Eye Rests"
        )

        L10n.languageOverride = "zh-Hans"
        XCTAssertEqual(
            L10n.format("onboarding.useSelectedWithPreset", "更多护眼休息"),
            "使用更多护眼休息开始"
        )
    }

    func testBlockedActionNotificationsUseUserActionLanguage() {
        defer { L10n.languageOverride = nil }

        L10n.languageOverride = "en"
        XCTAssertEqual(L10n.tr("menu.reset"), "Reset Schedule")
        XCTAssertEqual(L10n.tr("menu.emergencyOverlayOnly"), "Use Emergency Exit in the overlay")
        XCTAssertTrue(L10n.tr("menu.emergencyOverlayOnlyHelp").contains("This menu cannot exit"))
        XCTAssertTrue(L10n.tr("menu.emergencyOverlayOnlyHelp").contains("lower-right Emergency Exit twice"))
        XCTAssertTrue(L10n.tr("menu.emergencyOverlayOnlyHelp").contains("Esc twice"))
        XCTAssertEqual(
            L10n.tr("status.eyeGateActiveGuidance"),
            "Click Emergency Exit twice in the overlay, or press Esc twice."
        )
        XCTAssertEqual(L10n.tr("status.eyeGateActiveNoEmergencyGuidance"), "Keep looking away until the timer ends.")
        XCTAssertEqual(L10n.tr("status.eyeGateReadyGuidance"), "Finish from the overlay when ready.")
        XCTAssertEqual(
            L10n.tr("status.bodyBreakActiveGuidance"),
            "Use overlay controls to postpone, skip, or finish."
        )
        XCTAssertEqual(L10n.tr("prefs.reset"), "Reset Schedule")
        XCTAssertEqual(L10n.format("notification.quitBlocked", "Eye Gate"), "Finish Eye Gate before quitting.")
        XCTAssertEqual(
            L10n.tr("notification.quitBlockedEyeGateEmergency"),
            "Use Emergency Exit in the overlay to quit during Eye Gate. Click Emergency Exit twice or press Esc twice; this records a missed rest."
        )
        XCTAssertTrue(L10n.tr("notification.quitBlockedEyeGateEmergency").contains("Emergency Exit in the overlay"))
        XCTAssertTrue(L10n.tr("notification.quitBlockedEyeGateEmergency").contains("Emergency Exit twice"))
        XCTAssertTrue(L10n.tr("notification.quitBlockedEyeGateEmergency").contains("Esc twice"))
        XCTAssertTrue(L10n.tr("notification.quitBlockedEyeGateEmergency").contains("missed rest"))
        XCTAssertEqual(L10n.format("notification.resetBlocked", "Eye Gate"), "Finish Eye Gate before resetting the schedule.")
        XCTAssertEqual(L10n.format("notification.pauseBlocked", "Eye Gate"), "Finish Eye Gate before pausing.")
        XCTAssertFalse(L10n.tr("notification.quitBlocked").localizedCaseInsensitiveContains("strict"))
        XCTAssertFalse(L10n.tr("notification.quitBlockedEyeGateEmergency").localizedCaseInsensitiveContains("hold"))
        XCTAssertFalse(L10n.tr("notification.quitBlockedEyeGateEmergency").localizedCaseInsensitiveContains("another window"))
        XCTAssertFalse(L10n.tr("notification.resetBlocked").localizedCaseInsensitiveContains("strict"))
        XCTAssertFalse(L10n.tr("notification.pauseBlocked").localizedCaseInsensitiveContains("strict"))
        XCTAssertFalse(L10n.tr("notification.resetBlocked").localizedCaseInsensitiveContains("breaks"))

        L10n.languageOverride = "zh-Hans"
        XCTAssertEqual(L10n.tr("menu.reset"), "重置计划")
        XCTAssertEqual(L10n.tr("menu.emergencyOverlayOnly"), "在覆盖层内使用紧急退出")
        XCTAssertTrue(L10n.tr("menu.emergencyOverlayOnlyHelp").contains("此菜单不能退出"))
        XCTAssertTrue(L10n.tr("menu.emergencyOverlayOnlyHelp").contains("右下角"))
        XCTAssertTrue(L10n.tr("menu.emergencyOverlayOnlyHelp").contains("紧急退出两次"))
        XCTAssertTrue(L10n.tr("menu.emergencyOverlayOnlyHelp").contains("两次 Esc"))
        XCTAssertEqual(L10n.tr("status.eyeGateActiveGuidance"), "在覆盖层内点击紧急退出两次，或按两次 Esc。")
        XCTAssertEqual(L10n.tr("status.eyeGateActiveNoEmergencyGuidance"), "计时结束前，请继续看向屏幕外。")
        XCTAssertEqual(L10n.tr("status.eyeGateReadyGuidance"), "准备好后，从覆盖层内完成休息。")
        XCTAssertEqual(L10n.tr("status.bodyBreakActiveGuidance"), "使用覆盖层按钮推迟、跳过或完成。")
        XCTAssertEqual(L10n.tr("prefs.reset"), "重置计划")
        XCTAssertEqual(L10n.format("notification.quitBlocked", "护眼休息"), "请先完成护眼休息，再退出。")
        XCTAssertEqual(
            L10n.tr("notification.quitBlockedEyeGateEmergency"),
            "要在护眼休息中退出，请在覆盖层内点击紧急退出两次，或按两次 Esc；这会记录一次未完成休息。"
        )
        XCTAssertTrue(L10n.tr("notification.quitBlockedEyeGateEmergency").contains("覆盖层内点击紧急退出两次"))
        XCTAssertTrue(L10n.tr("notification.quitBlockedEyeGateEmergency").contains("两次 Esc"))
        XCTAssertTrue(L10n.tr("notification.quitBlockedEyeGateEmergency").contains("未完成休息"))
        XCTAssertEqual(L10n.format("notification.resetBlocked", "护眼休息"), "请先完成护眼休息，再重置计划。")
        XCTAssertEqual(L10n.format("notification.pauseBlocked", "护眼休息"), "请先完成护眼休息，再暂停。")
        XCTAssertFalse(L10n.tr("notification.quitBlocked").contains("严格"))
        XCTAssertFalse(L10n.tr("notification.quitBlockedEyeGateEmergency").contains("长按"))
        XCTAssertFalse(L10n.tr("notification.quitBlockedEyeGateEmergency").contains("另一个窗口"))
        XCTAssertFalse(L10n.tr("notification.resetBlocked").contains("严格"))
        XCTAssertFalse(L10n.tr("notification.pauseBlocked").contains("严格"))
    }

    func testRestoreDefaultsConfirmationNamesTheDestructiveAction() {
        defer { L10n.languageOverride = nil }

        L10n.languageOverride = "en"
        XCTAssertEqual(L10n.tr("prefs.restoreDefaultsContinue"), "Restore Defaults")
        XCTAssertTrue(L10n.tr("prefs.restoreDefaultsWarning").contains("current preferences"))
        XCTAssertFalse(L10n.tr("prefs.restoreDefaultsContinue").localizedCaseInsensitiveContains("continue"))

        L10n.languageOverride = "zh-Hans"
        XCTAssertEqual(L10n.tr("prefs.restoreDefaultsContinue"), "恢复默认")
        XCTAssertTrue(L10n.tr("prefs.restoreDefaultsWarning").contains("当前偏好设置"))
        XCTAssertFalse(L10n.tr("prefs.restoreDefaultsContinue").contains("继续"))
    }

    private func simplifiedChineseLocalizedValues() throws -> [String] {
        try localizedValues(language: "zh-Hans")
    }

    private func localizedValues(language: String) throws -> [String] {
        let testFileURL = URL(fileURLWithPath: #filePath)
        let packageRoot = testFileURL
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let stringsURL = packageRoot
            .appendingPathComponent("Sources/shouldrest/Resources/\(language).lproj/Localizable.strings")
        let content = try String(contentsOf: stringsURL, encoding: .utf8)
        return content
            .components(separatedBy: .newlines)
            .compactMap { line in
                guard let separatorRange = line.range(of: "=") else { return nil }
                return String(line[separatorRange.upperBound...])
            }
    }
}
